/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matjarokom.ui.view;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import matjarokom.Control.com.RoundedLineBorder;
import matjarokom.Model.com.Categorie;
import matjarokom.Model.com.Stocke;
import matjarokom.Model.com.Unit;
import matjarokom.Model.com.produit_stock;

/**
 *
 * @author farid
 */
public class AddProductView extends javax.swing.JDialog {

     produit_stock produitstockGetDat=new produit_stock(),produitstockSetDat;
    Unit unit_GetData=new Unit();
    unitView unitView;
    
    Stocke stockGetData=new Stocke();
    JFileChooser chooserfile;
    File ProduitPicture;
    Categorie categorieGetData=new Categorie(),categorieSetData=null;
    // private File ProduitPicture;
     RoundedLineBorder roundedLineBorder =new RoundedLineBorder(Color.BLACK, 1, 10, true);
     JTextField[] ListText;
     Home homeApp;
    public AddProductView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.unitView = new unitView(this, true); // initialise Window UnitView
        initComponents();
        
        this.ListText = 
            new JTextField[]{Ref_produit, Desg_produit, Prix_Achat_prd, prixVente_produit, 
            QuantityStok_produit, NbrPcsInQty_produit, MinStok_produit, Postion_produit, Stock_produit, 
            TxtPrdPrix9, Forns_produit};
        ((JLabel) LocalStock.getRenderer()).setHorizontalAlignment(JLabel.CENTER);
        ((JLabel) Catg_produit_cmb.getRenderer()).setHorizontalAlignment(JLabel.CENTER);
        ((JLabel) UnitForQuantity_produit.getRenderer()).setHorizontalAlignment(JLabel.CENTER);
        ((JLabel) Unit_produit.getRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
          HintTextField(ListText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageProduit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ref_produit = new javax.swing.JTextField();
        Frn_ID15 = new javax.swing.JLabel();
        Frn_ID5 = new javax.swing.JLabel();
        Desg_produit = new javax.swing.JTextField();
        QuantityStok_produit = new javax.swing.JTextField();
        Frn_ID29 = new javax.swing.JLabel();
        UnitForQuantity_produit = new javax.swing.JComboBox<>();
        Frn_ID28 = new javax.swing.JLabel();
        Nbr_Pcs_label1 = new javax.swing.JLabel();
        NbrPcsInQty_produit = new javax.swing.JTextField();
        Frn_ID6 = new javax.swing.JLabel();
        UnitCntMulPcs = new javax.swing.JCheckBox();
        Prix_Achat_prd = new javax.swing.JTextField();
        Frn_ID11 = new javax.swing.JLabel();
        prixVente_produit = new javax.swing.JTextField();
        Catg_produit_cmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Frn_ID9 = new javax.swing.JLabel();
        Frn_ID12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Frn_ID30 = new javax.swing.JLabel();
        Frn_ID31 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Frn_ID13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Frn_ID32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Frn_ID19 = new javax.swing.JLabel();
        Frn_ID24 = new javax.swing.JLabel();
        Forns_produit = new javax.swing.JTextField();
        TxtPrdPrix9 = new javax.swing.JTextField();
        Frn_ID23 = new javax.swing.JLabel();
        Frn_ID22 = new javax.swing.JLabel();
        MinStok_produit = new javax.swing.JTextField();
        Frn_ID21 = new javax.swing.JLabel();
        Postion_produit = new javax.swing.JTextField();
        Frn_ID10 = new javax.swing.JLabel();
        LocalStock = new javax.swing.JComboBox<>();
        Stock_produit = new javax.swing.JTextField();
        Unit_produit = new javax.swing.JComboBox<>();
        CheckDateExp_produit = new javax.swing.JCheckBox();
        DateDormatField = new javax.swing.JFormattedTextField();
        Nbr_Pcs_label2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarque_produit = new javax.swing.JTextArea();
        ShowScreen_produit = new javax.swing.JCheckBox();
        ShowScreen_produit1 = new javax.swing.JCheckBox();
        Frn_ID25 = new javax.swing.JLabel();
        buttonView4 = new matjarokom.ui.view.ButtonView();
        buttonView1 = new matjarokom.ui.view.ButtonView();
        buttonView2 = new matjarokom.ui.view.ButtonView();
        buttonView3 = new matjarokom.ui.view.ButtonView();
        buttonView6 = new matjarokom.ui.view.ButtonView();
        buttonView7 = new matjarokom.ui.view.ButtonView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 230, 210));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ImageProduit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ImageProduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/addimgPrd2.png"))); // NOI18N
        ImageProduit.setText("الصورة");
        ImageProduit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ImageProduit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImageProduit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageProduit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ImageProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImageProduitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImageProduitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImageProduitMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(230, 230, 210));
        jPanel2.setBorder(roundedLineBorder);

        Ref_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ref_produit.setForeground(new java.awt.Color(204, 204, 204));
        Ref_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Ref_produit.setText("الباركـود");
        Ref_produit.setBorder(roundedLineBorder);
        Ref_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Ref_produitKeyPressed(evt);
            }
        });

        Frn_ID15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID15.setText("الباركـود        :");

        Frn_ID5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID5.setText(" اسم المنتج    :");

        Desg_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Desg_produit.setForeground(new java.awt.Color(204, 204, 204));
        Desg_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Desg_produit.setText("اسم المنتج");
        Desg_produit.setBorder(roundedLineBorder);
        Desg_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Desg_produitKeyPressed(evt);
            }
        });

        QuantityStok_produit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        QuantityStok_produit.setForeground(new java.awt.Color(204, 204, 204));
        QuantityStok_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityStok_produit.setText("00");
        QuantityStok_produit.setBorder(roundedLineBorder);
        QuantityStok_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantityStok_produitKeyPressed(evt);
            }
        });

        Frn_ID29.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID29.setText("الوحدة ");

        UnitForQuantity_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        UnitForQuantity_produit.setBorder(null);
        UnitForQuantity_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnitForQuantity_produit.setOpaque(false);
        UnitForQuantity_produit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UnitForQuantity_produitItemStateChanged(evt);
            }
        });
        UnitForQuantity_produit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitForQuantity_produitActionPerformed(evt);
            }
        });
        UnitForQuantity_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UnitForQuantity_produitKeyPressed(evt);
            }
        });

        Frn_ID28.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID28.setText("عدد الوحدات الداخلية");

        Nbr_Pcs_label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nbr_Pcs_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nbr_Pcs_label1.setText("سعر شراء ");

        NbrPcsInQty_produit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        NbrPcsInQty_produit.setForeground(new java.awt.Color(204, 204, 204));
        NbrPcsInQty_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NbrPcsInQty_produit.setText("00");
        NbrPcsInQty_produit.setBorder(roundedLineBorder);
        NbrPcsInQty_produit.setEnabled(false);
        NbrPcsInQty_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NbrPcsInQty_produitKeyPressed(evt);
            }
        });

        Frn_ID6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID6.setText("التصنيف");

        UnitCntMulPcs.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        UnitCntMulPcs.setText("يحتوي علي وحدات صغيرة");
        UnitCntMulPcs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnitCntMulPcs.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        UnitCntMulPcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitCntMulPcsActionPerformed(evt);
            }
        });

        Prix_Achat_prd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Prix_Achat_prd.setForeground(new java.awt.Color(204, 204, 204));
        Prix_Achat_prd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Prix_Achat_prd.setText("00.00");
        Prix_Achat_prd.setBorder(roundedLineBorder);
        Prix_Achat_prd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Prix_Achat_prdKeyPressed(evt);
            }
        });

        Frn_ID11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID11.setText("سعر بيع ");

        prixVente_produit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        prixVente_produit.setForeground(new java.awt.Color(204, 204, 204));
        prixVente_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixVente_produit.setText("00.00");
        prixVente_produit.setBorder(roundedLineBorder);

        Catg_produit_cmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Catg_produit_cmbKeyPressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        Frn_ID9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID9.setText("كمية الشراء");

        Frn_ID12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Frn_ID12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID12.setText("السعر الاجمالي للشراء");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("00.00");

        Frn_ID30.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID30.setText("وحدة");

        Frn_ID31.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID31.setText("قطعــة");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("الوحدة");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("الوحدة");
        jLabel9.setOpaque(true);

        Frn_ID13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID13.setText("سعر شراء القطعة");

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("00");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("الوحدة");
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("القطعة");
        jLabel11.setOpaque(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "علبة", "حبة" }));

        Frn_ID32.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID32.setText("الوحدة الصغيرة");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Frn_ID12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nbr_Pcs_label1))
                                    .addComponent(Prix_Achat_prd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(Frn_ID13))
                                    .addGap(114, 114, 114)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Frn_ID11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prixVente_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ref_produit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Frn_ID6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 274, Short.MAX_VALUE)
                                .addComponent(Frn_ID5))
                            .addComponent(Desg_produit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Catg_produit_cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Frn_ID31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 38, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Frn_ID29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UnitCntMulPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UnitForQuantity_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Frn_ID28))
                                    .addComponent(NbrPcsInQty_produit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Frn_ID32, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Frn_ID30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Frn_ID9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addComponent(QuantityStok_produit))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Frn_ID15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ref_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Frn_ID5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Desg_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(Frn_ID6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Catg_produit_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UnitCntMulPcs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UnitForQuantity_produit))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Frn_ID9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Frn_ID31, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NbrPcsInQty_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Frn_ID30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QuantityStok_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Frn_ID28)
                            .addComponent(Frn_ID32))
                        .addGap(46, 46, 46)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Frn_ID12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(Nbr_Pcs_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Frn_ID13, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Prix_Achat_prd)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Frn_ID11)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prixVente_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        jPanel3.setBackground(new java.awt.Color(230, 230, 210));
        jPanel3.setBorder(roundedLineBorder);

        Frn_ID19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID19.setText("مكان المنتج :");

        Frn_ID24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID24.setText("الموردين :");

        Forns_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Forns_produit.setForeground(new java.awt.Color(204, 204, 204));
        Forns_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Forns_produit.setText("اسم المورد");
        Forns_produit.setBorder(roundedLineBorder);

        TxtPrdPrix9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix9.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix9.setText("رقم الفاتورة / رقم وصل الشراء");
        TxtPrdPrix9.setBorder(roundedLineBorder);

        Frn_ID23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID23.setText("فوتير الشراء :");

        Frn_ID22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID22.setText("كمية اعادة الطلب :");

        MinStok_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MinStok_produit.setForeground(new java.awt.Color(204, 204, 204));
        MinStok_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MinStok_produit.setText("00");
        MinStok_produit.setBorder(roundedLineBorder);
        MinStok_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MinStok_produitKeyPressed(evt);
            }
        });

        Frn_ID21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID21.setText("الكمية المتاحة   :");

        Postion_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Postion_produit.setForeground(new java.awt.Color(204, 204, 204));
        Postion_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Postion_produit.setText("تحديد المكان المخصص للمنتج");
        Postion_produit.setBorder(roundedLineBorder);
        Postion_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Postion_produitKeyPressed(evt);
            }
        });

        Frn_ID10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID10.setText("المخزن :");

        LocalStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LocalStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LocalStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LocalStockKeyPressed(evt);
            }
        });

        Stock_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Stock_produit.setForeground(new java.awt.Color(204, 204, 204));
        Stock_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Stock_produit.setText("00");
        Stock_produit.setBorder(roundedLineBorder);
        Stock_produit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Stock_produitKeyPressed(evt);
            }
        });

        Unit_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Unit_produit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));
        Unit_produit.setBorder(null);
        Unit_produit.setOpaque(false);

        CheckDateExp_produit.setBackground(new java.awt.Color(255, 255, 255));
        CheckDateExp_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CheckDateExp_produit.setText("منتج له تاريخ الصلاحية ");
        CheckDateExp_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckDateExp_produit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            DateDormatField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DateDormatField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Nbr_Pcs_label2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nbr_Pcs_label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nbr_Pcs_label2.setText("القطع داخل الوحدة");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/load_h 28.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/load_h 28.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPrdPrix9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Frn_ID23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Frn_ID10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Postion_produit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LocalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Unit_produit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Stock_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(DateDormatField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckDateExp_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(MinStok_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nbr_Pcs_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Forns_produit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Frn_ID24)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Frn_ID22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LocalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Postion_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Unit_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID23, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPrdPrix9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID24)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Forns_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Nbr_Pcs_label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateDormatField)
                    .addComponent(CheckDateExp_produit, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("اضافة منتج جديد");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("خصائص متقدمة");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        remarque_produit.setColumns(20);
        remarque_produit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        remarque_produit.setForeground(new java.awt.Color(255, 255, 255));
        remarque_produit.setRows(4);
        remarque_produit.setText("\n");
        remarque_produit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الوصف", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        remarque_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        remarque_produit.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        remarque_produit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remarque_produitFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(remarque_produit);

        ShowScreen_produit.setBackground(new java.awt.Color(3, 4, 27));
        ShowScreen_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowScreen_produit.setForeground(new java.awt.Color(255, 255, 255));
        ShowScreen_produit.setText("اظهار المنتج في شاشة المبيعات");
        ShowScreen_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowScreen_produit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ShowScreen_produit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ShowScreen_produit1.setBackground(new java.awt.Color(3, 4, 27));
        ShowScreen_produit1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowScreen_produit1.setForeground(new java.awt.Color(255, 255, 255));
        ShowScreen_produit1.setSelected(true);
        ShowScreen_produit1.setText("اظهار اشعارات تخص المنتج ");
        ShowScreen_produit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowScreen_produit1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ShowScreen_produit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Frn_ID25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID25.setText("اضف الملاحظــة   :");

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("تحميل الصورة");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView4.setRounded(true);

        buttonView1.setBackground(new java.awt.Color(153, 0, 0));
        buttonView1.setForeground(new java.awt.Color(255, 255, 255));
        buttonView1.setText("حفظ");
        buttonView1.setBackgroundPainted(true);
        buttonView1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView1.setRounded(true);
        buttonView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView1ActionPerformed(evt);
            }
        });

        buttonView2.setBackground(new java.awt.Color(0, 102, 102));
        buttonView2.setForeground(new java.awt.Color(255, 255, 255));
        buttonView2.setText("الرئيســية");
        buttonView2.setBackgroundPainted(true);
        buttonView2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView2.setRounded(true);

        buttonView3.setBackground(new java.awt.Color(0, 102, 102));
        buttonView3.setForeground(new java.awt.Color(255, 255, 255));
        buttonView3.setText("مسح");
        buttonView3.setBackgroundPainted(true);
        buttonView3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView3.setRounded(true);
        buttonView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView3ActionPerformed(evt);
            }
        });

        buttonView6.setBackground(new java.awt.Color(0, 102, 102));
        buttonView6.setForeground(new java.awt.Color(255, 255, 255));
        buttonView6.setText("الغـاء");
        buttonView6.setBackgroundPainted(true);
        buttonView6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView6.setRounded(true);

        buttonView7.setBackground(new java.awt.Color(0, 102, 102));
        buttonView7.setForeground(new java.awt.Color(255, 255, 255));
        buttonView7.setText("خروج");
        buttonView7.setBackgroundPainted(true);
        buttonView7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView7.setRounded(true);
        buttonView7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonView4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(ImageProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Frn_ID25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShowScreen_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShowScreen_produit))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(buttonView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonView2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonView3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonView6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ImageProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ShowScreen_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowScreen_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Frn_ID25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(buttonView2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonView6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonView7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImageProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseClicked

        UIManager.put("FileChooser.cancelButtonText","الغاء");
        JFileChooser chooserfile = new JFileChooser();
        chooserfile.setApproveButtonText("حفظ");
        int valShoice=chooserfile.showDialog(this,"اختر صورة المنتج");
        //int valShoice=chooserfile.showOpenDialog(this);

        if (valShoice==JFileChooser.APPROVE_OPTION) {
            //ProduitImageDesc=
            ProduitPicture=chooserfile.getSelectedFile();  // select
            ImageProduit.setText("");

            ImageIcon imageIcon = new ImageIcon(new ImageIcon(ProduitPicture.getAbsolutePath()).getImage().getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_DEFAULT));
            ImageProduit.setIcon(imageIcon);
            //ImageProduit.setIcon( new ImageIcon(ProduitImageDesc.getAbsolutePath()).getImage().getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_DEFAULT));  // set Icon to produit label
        }else{

            ImageIcon imageIcon = new ImageIcon(getClass().getResource("/imgs/addimgPrd2.png"));

            ImageProduit.setIcon(imageIcon);
            ImageProduit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            ImageProduit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            ImageProduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }//GEN-LAST:event_ImageProduitMouseClicked

    
    public void FillDataStockLocal(){
        LocalStock.removeAllItems();
        Iterator<Stocke> itr=stockGetData.GetlistDataLocaleStock().iterator();
        Stocke next;
        while (itr.hasNext()) {
            next = itr.next();
            LocalStock.addItem(next.getLocale_Stocke());
        }
        itr=null;
        next=null;
    }
    /*************************************/
       public void FillDataUnits(){
        UnitForQuantity_produit.removeAllItems();
        
        Iterator<Unit> itr=unit_GetData.GetlistDataUnits().iterator();
        Unit next;
        while (itr.hasNext()) {
            next = itr.next();
            UnitForQuantity_produit.addItem(next.getUnit_Name());
        }
        itr=null;
        next=null;
    }
    /***************************************/
    public void FillDataCategorie(){
    Catg_produit_cmb.removeAllItems();
    categorieGetData.GetListOfCategories(); // fill arrayList for Categories
    Iterator<Categorie> itr=categorieGetData.getListCategorie().iterator(); // get ArrayList.To Iterator()
    Categorie next;
    
    while (itr.hasNext()) {
            next = itr.next();
            Catg_produit_cmb.addItem(next.getName_Ctg());
        }
    }
    
    private void ImageProduitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseEntered
        //     jLabel2.setVisible(true);
    }//GEN-LAST:event_ImageProduitMouseEntered

    private void ImageProduitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseExited
        //  jLabel2.setVisible(false);
    }//GEN-LAST:event_ImageProduitMouseExited

    private void remarque_produitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remarque_produitFocusGained
        remarque_produit.setText("");
    }//GEN-LAST:event_remarque_produitFocusGained

    private void buttonView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonView3ActionPerformed

    private void buttonView7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonView7ActionPerformed

    private void buttonView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView1ActionPerformed
      CreateProduitByCompenent();// function to create New  Product with compenents 
      produitstockSetDat.AddProduit();
    }//GEN-LAST:event_buttonView1ActionPerformed

    private void Ref_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ref_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && 
                (!Ref_produit.getText().equals("الباركـود") && !Ref_produit.getText().equals(""))) {
            Desg_produit.requestFocus();
        } 
    }//GEN-LAST:event_Ref_produitKeyPressed

    private void Desg_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Desg_produitKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ENTER && 
                (!Desg_produit.getText().equals("اسم المنتج") && !Desg_produit.getText().equals(""))) {
            Catg_produit_cmb.requestFocus();
            Catg_produit_cmb.showPopup();
        } 
    }//GEN-LAST:event_Desg_produitKeyPressed

    private void Catg_produit_cmbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Catg_produit_cmbKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER ) {
            UnitForQuantity_produit.requestFocus();
            
        } 
    }//GEN-LAST:event_Catg_produit_cmbKeyPressed

    private void Prix_Achat_prdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prix_Achat_prdKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ENTER && 
                (!Prix_Achat_prd.getText().equals("00.00") && !Prix_Achat_prd.getText().equals(""))) {
            jTextField1.setText(Integer.valueOf(QuantityStok_produit.getText())* Float.valueOf(Prix_Achat_prd.getText())+"");
            jTextField2.setText(Integer.valueOf(Prix_Achat_prd.getText())/ Float.valueOf(NbrPcsInQty_produit.getText())+"");
            
            prixVente_produit.requestFocus();
        } 
    }//GEN-LAST:event_Prix_Achat_prdKeyPressed

    private void UnitCntMulPcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitCntMulPcsActionPerformed
        if (UnitCntMulPcs.isSelected()) {
            NbrPcsInQty_produit.setEnabled(true);
            Nbr_Pcs_label1.setEnabled(true);
            jLabel8.setText((String) UnitForQuantity_produit.getSelectedItem());
            jLabel9.setText((String) UnitForQuantity_produit.getSelectedItem());
            
        }else {
            NbrPcsInQty_produit.setEnabled(false);
            Nbr_Pcs_label1.setEnabled(false);
            jLabel8.setText("الوحدة");
            jLabel9.setText("الوحدة");
        }
    }//GEN-LAST:event_UnitCntMulPcsActionPerformed

    private void QuantityStok_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityStok_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && (!QuantityStok_produit.getText().equals("00") && !QuantityStok_produit.getText().equals(""))) {
            Frn_ID30.setText((String) UnitForQuantity_produit.getSelectedItem());
            
            if (UnitCntMulPcs.isSelected()) 
                NbrPcsInQty_produit.requestFocus();
            else MinStok_produit.requestFocus();
        }
    }//GEN-LAST:event_QuantityStok_produitKeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jPanel3.setEnabled(true);
        }else {
        jPanel3.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void MinStok_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MinStok_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && !MinStok_produit.getText().equals("00") && !MinStok_produit.getText().equals("")) {
            LocalStock.requestFocus();
            LocalStock.showPopup();
        }
    }//GEN-LAST:event_MinStok_produitKeyPressed

    private void LocalStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocalStockKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            Postion_produit.requestFocus();
        }
    }//GEN-LAST:event_LocalStockKeyPressed

    private void Postion_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Postion_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER &&
                !Postion_produit.getText().equals("تحديد المكان المخصص للمنتج") && !Postion_produit.getText().equals("") ) {
           Stock_produit.requestFocus();
           
        }
    }//GEN-LAST:event_Postion_produitKeyPressed

    private void Stock_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Stock_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER ) { // In This case Can  still Qty ==0
            Unit_produit.requestFocus();
        }
    }//GEN-LAST:event_Stock_produitKeyPressed

    private void UnitForQuantity_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnitForQuantity_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER ) { // In This case Can  still Qty ==0
            UnitCntMulPcs.requestFocus();
        }
    }//GEN-LAST:event_UnitForQuantity_produitKeyPressed

    private void NbrPcsInQty_produitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NbrPcsInQty_produitKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER && !NbrPcsInQty_produit.getText().equals("00") && !NbrPcsInQty_produit.getText().equals("")) {
            if(Integer.valueOf(NbrPcsInQty_produit.getText())<10 && Integer.valueOf(NbrPcsInQty_produit.getText())!=1){
            
            Frn_ID31.setText("قطع");
            }else Frn_ID31.setText("قطعة");
            
            Prix_Achat_prd.requestFocus();
        }
    }//GEN-LAST:event_NbrPcsInQty_produitKeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        unitView.DisplayData_in_GUI_Unit();
        unitView.FillSousUnit();
        
        unitView.setVisible(true);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void UnitForQuantity_produitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitForQuantity_produitActionPerformed
        // In This case Can  still Qty ==0
            
            byte typeUnt;
         typeUnt = unit_GetData.getTyp_unit();
        if (typeUnt==1) {
            JOptionPane.showMessageDialog(null, "Test Event in combbox");
            String SousUnit=unit_GetData.GetSousUnit((String) UnitForQuantity_produit.getSelectedItem());
            NbrPcsInQty_produit.setEnabled(true);
            Nbr_Pcs_label1.setEnabled(true);
            jLabel8.setText(SousUnit);
            jLabel9.setText(SousUnit);
        }
        
        //UnitCntMulPcs.requestFocus(); 
    }//GEN-LAST:event_UnitForQuantity_produitActionPerformed

    private void UnitForQuantity_produitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UnitForQuantity_produitItemStateChanged
         byte typeUnt;
         typeUnt = unit_GetData.GetTypeUniteByName((String) UnitForQuantity_produit.getSelectedItem());
        if (typeUnt==1) {
            JOptionPane.showMessageDialog(null, "Test Event in combbox");
            String SousUnit=unit_GetData.GetSousUnit((String) UnitForQuantity_produit.getSelectedItem());
            NbrPcsInQty_produit.setEnabled(true);
            Nbr_Pcs_label1.setEnabled(true);
            jLabel8.setText(SousUnit);
            jLabel9.setText(SousUnit);
        }
        
        //UnitCntMulPcs.requestFocus(); 
    }//GEN-LAST:event_UnitForQuantity_produitItemStateChanged
     public void CreateProduitByCompenent(){
    
        String DesgProduit=Desg_produit.getText();// Des prod
        String RefProduit=Ref_produit.getText(); // get Ref produit
        String NamCatg=(String) Catg_produit_cmb.getSelectedItem();
        int id_categorie=categorieGetData.GetIdCategorie(NamCatg); // id catgorie
        int QuantityStock=Integer.valueOf(QuantityStok_produit.getText()); //QuantityInStock
        
        Date DateExpirProduit;
        
        String StringDate=DateDormatField.getText();
        try {
             DateExpirProduit=new SimpleDateFormat("dd/MM/yyyy").parse(StringDate);   //create Date expiration Of product
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "The Date Entree is Not Valid please verify ");
            return;
        }
        
        double Prix_Vente=Double.valueOf(prixVente_produit.getText()); // Prix vente prod
        double Prix_Achat;
        Prix_Achat = Double.parseDouble(Prix_Achat_prd.getText());
        int Id_Unit;
        
        Id_Unit=unit_GetData.GetIdUnit((String)UnitForQuantity_produit.getSelectedItem());
        String Stocke=(String) LocalStock.getSelectedItem();   // Nom locale de stockage
        int id_Stock;
        id_Stock = stockGetData.GetIdStockLocal(Stocke);
        
        
        //Id_Stocke
      
        
        //int NbrPcsInQty_prd=Integer.valueOf(NbrPcsInQty_produit.getText());  /// nbr pcs in unit stockeé dans le stock get From arrivageLine 
        
        String Postion_produit_in_stock=Postion_produit.getText();// position in stock position // 1 ere etage
        
        int MinStok_produit_in_stock=Integer.valueOf(MinStok_produit.getText());// get Min Stock for produit
        //double LastDateAchat_prod=Double.valueOf(LastDateAchat_produit.getText()); // last Date Bye for product 
        
        boolean check; // check prod in viewForm 
        
        
      check= ShowScreen_produit.isSelected();   //check in panel access product
        
      String RemarqueProduit=remarque_produit.getText(); //get Remarque about Product
      FileInputStream in = null;
        try {
            in = new FileInputStream(ProduitPicture);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(produitView.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     produitstockSetDat=new produit_stock(1, DesgProduit, RefProduit, id_categorie, 
              QuantityStock, DateExpirProduit, Prix_Vente, Prix_Achat,MinStok_produit_in_stock,Id_Unit,
              id_Stock, Postion_produit_in_stock, check, RemarqueProduit,in);
                
    }
     
    public void CreateHintFields(){
        HintTextField(ListText);
    }
     
     
    public void HintTextField(JTextField[] TabTextField) {

        for (JTextField TextField : TabTextField) {
            TextField.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent e) {

//  new JTextField[]{  Ref_produit, Desg_produit, Prix_Achat_prd, prixVente_produit,
//                     QuantityStok_produit, NbrPcsInQty_produit, MinStok_produit, Postion_produit, Stock_produit, 
//                     TxtPrdPrix9, Forns_produit};
                    switch (TextField.getText()) {
                        case "الباركـود":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
//الدرجة
                        case "اسم المنتج":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
                        case "00.00":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
                        case "00":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
                        case "تحديد المكان المخصص للمنتج":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
                        case "رقم الفاتورة / رقم وصل الشراء":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
                        case "اسم المورد":
                            TextField.setText("");
                            TextField.setForeground(Color.black);
                            break;
                        default:
                            break;
                    }

                }

                @Override
                public void focusLost(FocusEvent e) {

                    if (TextField.equals(Ref_produit) && TextField.getText().equals("")) {
                        TextField.setText("الباركـود");
                        TextField.setForeground(new Color(204, 204, 204));
                    } else if (TextField.equals(Desg_produit) && TextField.getText().equals("")) {
                        TextField.setText("اسم المنتج");
                        TextField.setForeground(new Color(204, 204, 204));
                    } else if ((TextField.equals(prixVente_produit) || TextField.equals(Prix_Achat_prd)) && TextField.getText().equals("")) {
                        TextField.setText("00.00");
                        TextField.setForeground(new Color(204, 204, 204));
                    } else if ((TextField.equals(QuantityStok_produit)|| TextField.equals(NbrPcsInQty_produit) 
                            ||  TextField.equals(MinStok_produit) || TextField.equals(Stock_produit)) && TextField.getText().equals("")) {
                        TextField.setText("00");
                        TextField.setForeground(new Color(204, 204, 204));
                    } else if (TextField.equals(Postion_produit) && TextField.getText().equals("")) {
                        TextField.setText("تحديد المكان المخصص للمنتج");
                        TextField.setForeground(new Color(204, 204, 204));
                    } else if (TextField.equals(TxtPrdPrix9) && TextField.getText().equals("")) {
                        TextField.setText("رقم الفاتورة / رقم وصل الشراء");
                        TextField.setForeground(new Color(204, 204, 204));
                    }else if (TextField.equals(Forns_produit) && TextField.getText().equals("")) {
                        TextField.setText("اسم المورد");
                        TextField.setForeground(new Color(204, 204, 204));
                    }

                }
            });
        }

    }
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProductView dialog = new AddProductView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Catg_produit_cmb;
    private javax.swing.JCheckBox CheckDateExp_produit;
    private javax.swing.JFormattedTextField DateDormatField;
    private javax.swing.JTextField Desg_produit;
    private javax.swing.JTextField Forns_produit;
    private javax.swing.JLabel Frn_ID10;
    private javax.swing.JLabel Frn_ID11;
    private javax.swing.JLabel Frn_ID12;
    private javax.swing.JLabel Frn_ID13;
    private javax.swing.JLabel Frn_ID15;
    private javax.swing.JLabel Frn_ID19;
    private javax.swing.JLabel Frn_ID21;
    private javax.swing.JLabel Frn_ID22;
    private javax.swing.JLabel Frn_ID23;
    private javax.swing.JLabel Frn_ID24;
    private javax.swing.JLabel Frn_ID25;
    private javax.swing.JLabel Frn_ID28;
    private javax.swing.JLabel Frn_ID29;
    private javax.swing.JLabel Frn_ID30;
    private javax.swing.JLabel Frn_ID31;
    private javax.swing.JLabel Frn_ID32;
    private javax.swing.JLabel Frn_ID5;
    private javax.swing.JLabel Frn_ID6;
    private javax.swing.JLabel Frn_ID9;
    private javax.swing.JLabel ImageProduit;
    private javax.swing.JComboBox<String> LocalStock;
    private javax.swing.JTextField MinStok_produit;
    private javax.swing.JTextField NbrPcsInQty_produit;
    private javax.swing.JLabel Nbr_Pcs_label1;
    private javax.swing.JLabel Nbr_Pcs_label2;
    private javax.swing.JTextField Postion_produit;
    private javax.swing.JTextField Prix_Achat_prd;
    private javax.swing.JTextField QuantityStok_produit;
    private javax.swing.JTextField Ref_produit;
    private javax.swing.JCheckBox ShowScreen_produit;
    private javax.swing.JCheckBox ShowScreen_produit1;
    private javax.swing.JTextField Stock_produit;
    private javax.swing.JTextField TxtPrdPrix9;
    private javax.swing.JCheckBox UnitCntMulPcs;
    private javax.swing.JComboBox<String> UnitForQuantity_produit;
    private javax.swing.JComboBox<String> Unit_produit;
    private matjarokom.ui.view.ButtonView buttonView1;
    private matjarokom.ui.view.ButtonView buttonView2;
    private matjarokom.ui.view.ButtonView buttonView3;
    private matjarokom.ui.view.ButtonView buttonView4;
    private matjarokom.ui.view.ButtonView buttonView6;
    private matjarokom.ui.view.ButtonView buttonView7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField prixVente_produit;
    private javax.swing.JTextArea remarque_produit;
    // End of variables declaration//GEN-END:variables
}
