/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matjarokom.ui.view;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import matjarokom.Control.com.RoundedLineBorder;
import matjarokom.Model.com.Categorie;
import matjarokom.Model.com.Stocke;
import matjarokom.Model.com.Unit;
import matjarokom.Model.com.produit_stock;

/**
 *
 * @author farid
 */
public class FormAddProduct extends javax.swing.JFrame {
    
    private File ProduitPicture;
    produit_stock produitstockGetDat=new produit_stock(),produitstockSetDat;
    Unit unit_GetData=new Unit();
    Stocke stockGetData=new Stocke();
    Categorie categorieGetData=new Categorie(),categorieSetData=null;
    RoundedLineBorder roundedLineBorder =new RoundedLineBorder(Color.BLACK, 1, 10, true);
    AbstractAction ctrl_N,ctrl_D,ctrl_R,Ctrl_S;
    //ProductSpeedAdd SpeedAddPrdct=new ProductSpeedAdd();
    AddProductView add_prduct=new AddProductView(this, true); // form dialog to add product
    /**
     * Creates new form FormAddProduit
     */
    public FormAddProduct() {
        initComponents();
        
        jButton1.setMnemonic(KeyEvent.VK_A);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CenterPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Ref_produit = new javax.swing.JTextField();
        Frn_ID15 = new javax.swing.JLabel();
        Frn_ID5 = new javax.swing.JLabel();
        Desg_produit = new javax.swing.JTextField();
        QuantityStok_produit = new javax.swing.JTextField();
        Frn_ID29 = new javax.swing.JLabel();
        UnitForQuantity_produit = new javax.swing.JComboBox<>();
        Frn_ID28 = new javax.swing.JLabel();
        Nbr_Pcs_label1 = new javax.swing.JLabel();
        NbrPcsInQty_produit = new javax.swing.JTextField();
        Frn_ID6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarque_produit = new javax.swing.JTextArea();
        CheckDateExp_produit1 = new javax.swing.JCheckBox();
        Prix_Achat_prd = new javax.swing.JTextField();
        Frn_ID9 = new javax.swing.JLabel();
        Frn_ID11 = new javax.swing.JLabel();
        prixVente_produit = new javax.swing.JTextField();
        Catg_produit_cmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Frn_ID19 = new javax.swing.JLabel();
        Frn_ID24 = new javax.swing.JLabel();
        Forns_produit = new javax.swing.JTextField();
        TxtPrdPrix9 = new javax.swing.JTextField();
        Frn_ID23 = new javax.swing.JLabel();
        Frn_ID22 = new javax.swing.JLabel();
        MinStok_produit = new javax.swing.JTextField();
        Frn_ID21 = new javax.swing.JLabel();
        ShowScreen_produit = new javax.swing.JCheckBox();
        Postion_produit = new javax.swing.JTextField();
        Frn_ID10 = new javax.swing.JLabel();
        LocalStock = new javax.swing.JComboBox<>();
        Stock_produit = new javax.swing.JTextField();
        Unit_produit = new javax.swing.JComboBox<>();
        CheckDateExp_produit = new javax.swing.JCheckBox();
        DateDormatField = new javax.swing.JFormattedTextField();
        ShowScreen_produit1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductsTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ImageProduit = new javax.swing.JLabel();
        BtnInerSavUpd = new matjarokom.ui.view.ButtonView();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        check_update_add = new javax.swing.JCheckBox();
        SidePanel = new javax.swing.JPanel();
        BtnNewPrduct = new matjarokom.ui.view.ButtonView();
        buttonView1 = new matjarokom.ui.view.ButtonView();
        buttonView3 = new matjarokom.ui.view.ButtonView();
        buttonView4 = new matjarokom.ui.view.ButtonView();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        CenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        CenterPanel.setPreferredSize(new java.awt.Dimension(1230, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(roundedLineBorder);

        Ref_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ref_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ref_produit.setBorder(roundedLineBorder);

        Frn_ID15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID15.setText("الباركـود        :");

        Frn_ID5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID5.setText(" اسم المنتج    :");

        Desg_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Desg_produit.setForeground(new java.awt.Color(204, 204, 204));
        Desg_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Desg_produit.setBorder(roundedLineBorder);

        QuantityStok_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        QuantityStok_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityStok_produit.setText("20");
        QuantityStok_produit.setBorder(roundedLineBorder);

        Frn_ID29.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID29.setText("الوحدة ");

        UnitForQuantity_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UnitForQuantity_produit.setBorder(null);
        UnitForQuantity_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnitForQuantity_produit.setOpaque(false);

        Frn_ID28.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID28.setText("الكمية المتاحة");

        Nbr_Pcs_label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nbr_Pcs_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nbr_Pcs_label1.setText("القطع داخل الوحدة");

        NbrPcsInQty_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NbrPcsInQty_produit.setForeground(new java.awt.Color(204, 204, 204));
        NbrPcsInQty_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NbrPcsInQty_produit.setBorder(roundedLineBorder);

        Frn_ID6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID6.setText("التصنيف");

        remarque_produit.setColumns(20);
        remarque_produit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        remarque_produit.setRows(3);
        remarque_produit.setText("\n");
        remarque_produit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الوصف", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        remarque_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        remarque_produit.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        remarque_produit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remarque_produitFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(remarque_produit);

        CheckDateExp_produit1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        CheckDateExp_produit1.setText("تحتوي عدة قطع");
        CheckDateExp_produit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckDateExp_produit1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CheckDateExp_produit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Prix_Achat_prd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Prix_Achat_prd.setForeground(new java.awt.Color(204, 204, 204));
        Prix_Achat_prd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Prix_Achat_prd.setText("00");
        Prix_Achat_prd.setBorder(roundedLineBorder);

        Frn_ID9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID9.setText("سعر الشــراء");

        Frn_ID11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID11.setText("سعر البيع");

        prixVente_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prixVente_produit.setForeground(new java.awt.Color(204, 204, 204));
        prixVente_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixVente_produit.setText("00");
        prixVente_produit.setBorder(roundedLineBorder);

        Catg_produit_cmb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Frn_ID11)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(Frn_ID29))
                                    .addComponent(UnitForQuantity_produit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Desg_produit)
                                    .addComponent(Ref_produit)
                                    .addComponent(Catg_produit_cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(prixVente_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Prix_Achat_prd, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(99, 99, 99)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(Frn_ID6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Frn_ID5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Frn_ID15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Frn_ID9)))))
                                            .addComponent(CheckDateExp_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Nbr_Pcs_label1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(NbrPcsInQty_produit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Frn_ID28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuantityStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Frn_ID15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ref_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desg_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Frn_ID6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Catg_produit_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prix_Achat_prd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prixVente_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID29)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheckDateExp_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UnitForQuantity_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nbr_Pcs_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Frn_ID28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NbrPcsInQty_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(roundedLineBorder);

        Frn_ID19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID19.setText("مكان المنتج :");

        Frn_ID24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID24.setText("الموردين :");

        Forns_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Forns_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Forns_produit.setBorder(roundedLineBorder);

        TxtPrdPrix9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix9.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix9.setText("00");
        TxtPrdPrix9.setBorder(roundedLineBorder);

        Frn_ID23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID23.setText("فوتير الشراء :");

        Frn_ID22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID22.setText("كمية اعادة الطلب :");

        MinStok_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MinStok_produit.setForeground(new java.awt.Color(204, 204, 204));
        MinStok_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MinStok_produit.setText("00");
        MinStok_produit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Frn_ID21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID21.setText("الكمية المتاحة   :");

        ShowScreen_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowScreen_produit.setText("اظهار المنتج في شاشة المبيعات");
        ShowScreen_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowScreen_produit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ShowScreen_produit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Postion_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Postion_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Postion_produit.setBorder(roundedLineBorder);

        Frn_ID10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID10.setText("المخزن :");

        LocalStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LocalStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Stock_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Stock_produit.setForeground(new java.awt.Color(204, 204, 204));
        Stock_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Stock_produit.setText("00");
        Stock_produit.setBorder(roundedLineBorder);

        Unit_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Unit_produit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));
        Unit_produit.setBorder(null);
        Unit_produit.setOpaque(false);

        CheckDateExp_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CheckDateExp_produit.setText("منتج له تاريخ الصلاحية ");
        CheckDateExp_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckDateExp_produit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            DateDormatField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DateDormatField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ShowScreen_produit1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowScreen_produit1.setSelected(true);
        ShowScreen_produit1.setText("اظهار اشعارات تخص المنتج ");
        ShowScreen_produit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowScreen_produit1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ShowScreen_produit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Forns_produit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LocalStock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Unit_produit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Stock_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Frn_ID23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Postion_produit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Frn_ID10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinStok_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowScreen_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(Frn_ID24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(DateDormatField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckDateExp_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ShowScreen_produit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPrdPrix9))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Frn_ID22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LocalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Postion_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Frn_ID21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Unit_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stock_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID23, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(TxtPrdPrix9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Frn_ID24)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Forns_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateDormatField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckDateExp_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowScreen_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowScreen_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        ProductsTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "الكمية", "سعر البيع", "سعر الشراء", "وحدة الشراء", "اسم الصنف", "المنتج", "كود المنتج", "الرقم"
            }
        ));
        ProductsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProductsTable.setGridColor(new java.awt.Color(51, 0, 153));
        ProductsTable.setRowHeight(26);
        ProductsTable.setSelectionBackground(new java.awt.Color(51, 0, 51));
        ProductsTable.getTableHeader().setResizingAllowed(false);
        ProductsTable.getTableHeader().setReorderingAllowed(false);
        ProductsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ProductsTable);

        jButton1.setText("Click or press ALT-C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ImageProduit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ImageProduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/addimgPrd2.png"))); // NOI18N
        ImageProduit.setText("الصورة");
        ImageProduit.setBorder(roundedLineBorder);
        ImageProduit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImageProduit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageProduit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ImageProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImageProduitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImageProduitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImageProduitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ImageProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnInerSavUpd.setBackground(new java.awt.Color(102, 0, 0));
        BtnInerSavUpd.setForeground(new java.awt.Color(255, 255, 255));
        BtnInerSavUpd.setText("حفظ");
        BtnInerSavUpd.setBackgroundPainted(true);
        BtnInerSavUpd.setEnabled(false);
        BtnInerSavUpd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnInerSavUpd.setRounded(true);

        jLabel1.setText("العدد الكلي:");

        jLabel2.setText("عدد المنتجات:");

        check_update_add.setBackground(new java.awt.Color(255, 255, 255));
        check_update_add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        check_update_add.setText("تفعيل عمليات الاضافة و التعديل");
        check_update_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_update_add.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        check_update_add.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        check_update_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_update_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CenterPanelLayout = new javax.swing.GroupLayout(CenterPanel);
        CenterPanel.setLayout(CenterPanelLayout);
        CenterPanelLayout.setHorizontalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CenterPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnInerSavUpd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(check_update_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        CenterPanelLayout.setVerticalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPanelLayout.createSequentialGroup()
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnInerSavUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_update_add))))
                .addGap(71, 71, 71))
        );

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        SidePanel.setBackground(new java.awt.Color(255, 255, 255));
        SidePanel.setPreferredSize(new java.awt.Dimension(110, 684));

        BtnNewPrduct.setBackground(new java.awt.Color(102, 0, 0));
        BtnNewPrduct.setForeground(new java.awt.Color(255, 255, 255));
        BtnNewPrduct.setText("<html><b>منتج جديد</b><br> Ctrl N </html> ");
        BtnNewPrduct.setBackgroundPainted(true);
        BtnNewPrduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnNewPrduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNewPrduct.setRounded(true);
        BtnNewPrduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewPrductActionPerformed(evt);
            }
        });

        buttonView1.setBackground(new java.awt.Color(102, 0, 0));
        buttonView1.setForeground(new java.awt.Color(255, 255, 255));
        buttonView1.setText("تعديل");
        buttonView1.setBackgroundPainted(true);
        buttonView1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonView1.setRounded(true);

        buttonView3.setBackground(new java.awt.Color(102, 0, 0));
        buttonView3.setForeground(new java.awt.Color(255, 255, 255));
        buttonView3.setText("حذف");
        buttonView3.setBackgroundPainted(true);
        buttonView3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonView3.setRounded(true);

        buttonView4.setBackground(new java.awt.Color(102, 0, 0));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("اضافة سريعة");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonView4.setRounded(true);

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonView3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(buttonView4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(5, 5, 5))
                    .addComponent(BtnNewPrduct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(BtnNewPrduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        getContentPane().add(SidePanel, java.awt.BorderLayout.LINE_END);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 40));

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setBorder(null);
        jMenu2.setText("الشـــركة");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("العنوان");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setBorder(null);
        jMenu3.setText("الأصنــاف");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu3StateChanged(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(null);
        jMenu1.setText("عمـلاء و مورديـن");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu1);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setBorder(null);
        jMenu4.setText("المبيعـات");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setBorder(null);
        jMenu5.setText("المشتريــات");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setBorder(null);
        jMenu6.setText("القبــض و الصرف");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setBorder(null);
        jMenu7.setText("الحســـابات");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(255, 255, 255));
        jMenu8.setBorder(null);
        jMenu8.setText("اعدادات");
        jMenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu8);

        jMenu9.setBackground(new java.awt.Color(255, 255, 255));
        jMenu9.setBorder(null);
        jMenu9.setText("البحـث");
        jMenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu9);

        jMenu10.setBackground(new java.awt.Color(255, 255, 255));
        jMenu10.setBorder(null);
        jMenu10.setText("الخدمات");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu10);

        jMenu11.setBackground(new java.awt.Color(255, 255, 255));
        jMenu11.setBorder(null);
        jMenu11.setText("مسـاعدة");
        jMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu11);

        jMenu12.setBackground(new java.awt.Color(255, 255, 255));
        jMenu12.setBorder(null);
        jMenu12.setText("خروج");
        jMenu12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu12);

        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void CreateProduitByCompenent(){
    
        String DesgProduit=Desg_produit.getText();// Des prod
        String RefProduit=Ref_produit.getText(); // get Ref produit
        String NamCatg=(String) Catg_produit_cmb.getSelectedItem();
        int id_categorie=categorieGetData.GetIdCategorie(NamCatg); // id catgorie
        int QuantityStock=Integer.valueOf(QuantityStok_produit.getText()); //QuantityInStock
        
        Date DateExpirProduit;
        
        String StringDate=DateDormatField.getText();
        try {
             DateExpirProduit=new SimpleDateFormat("dd/MM/yyyy").parse(StringDate);   //create Date expiration Of product
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "The Date Entree is Not Valid please verify ");
            return;
        }
        
        double Prix_Vente=Double.valueOf(prixVente_produit.getText()); // Prix vente prod
        double Prix_Achat;
        Prix_Achat = Double.parseDouble(Prix_Achat_prd.getText());
        int Id_Unit;
        
        Id_Unit=unit_GetData.GetIdUnit((String)UnitForQuantity_produit.getSelectedItem());
        String Stocke=(String) LocalStock.getSelectedItem();   // Nom locale de stockage
        int id_Stock;
        id_Stock = stockGetData.GetIdStockLocal(Stocke);
        
        
        //Id_Stocke
      
        
        //int NbrPcsInQty_prd=Integer.valueOf(NbrPcsInQty_produit.getText());  /// nbr pcs in unit stockeé dans le stock get From arrivageLine 
        
        String Postion_produit_in_stock=Postion_produit.getText();// position in stock position // 1 ere etage
        
        int MinStok_produit_in_stock=Integer.valueOf(MinStok_produit.getText());// get Min Stock for produit
        //double LastDateAchat_prod=Double.valueOf(LastDateAchat_produit.getText()); // last Date Bye for product 
        
        boolean check; // check prod in viewForm 
        
        
      check= ShowScreen_produit.isSelected();   //check in panel access product
        
      String RemarqueProduit=remarque_produit.getText(); //get Remarque about Product
      FileInputStream in = null;
        try {
            in = new FileInputStream(ProduitPicture);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(produitView.class.getName()).log(Level.SEVERE, null, ex);
        }
    
     produitstockSetDat=new produit_stock(1, DesgProduit, RefProduit, id_categorie, 
              QuantityStock, DateExpirProduit, Prix_Vente, Prix_Achat,MinStok_produit_in_stock,Id_Unit,
              id_Stock, Postion_produit_in_stock, check, RemarqueProduit,in);
                
    }
    
    public void CreateShortKey(){
    ctrl_N=new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            
            add_prduct.FillDataCategorie();
            add_prduct.FillDataStockLocal();
            add_prduct.FillDataUnits();
            add_prduct.setLocationRelativeTo(null);
            add_prduct.setVisible(true);
        }
    };
        String aKey="Action";
        KeyStroke keStroke = KeyStroke.getKeyStroke("ctrl N");
        InputMap iMap;    
        iMap = BtnNewPrduct.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        iMap.put(keStroke, aKey);
        ActionMap actionMap = BtnNewPrduct.getActionMap();
        actionMap.put(aKey,ctrl_N ); 
        
    }
    
    public void CustomizeTableProduct(){
        ProductsTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        ProductsTable.getColumnModel().getColumn(1).setPreferredWidth(20);
        ProductsTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        ProductsTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        ProductsTable.getColumnModel().getColumn(7).setPreferredWidth(2);
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.LEFT);
        ProductsTable.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        ProductsTable.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        ProductsTable.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        ProductsTable.getColumnModel().getColumn(6).setCellRenderer(cellRenderer);
        cellRenderer.setHorizontalAlignment(JLabel.RIGHT);
        ProductsTable.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        ProductsTable.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        ProductsTable.getColumnModel().getColumn(5).setCellRenderer(cellRenderer);
        //ProductsTable
        
        JTableHeader tableHeader = ProductsTable.getTableHeader();
        
        tableHeader.setPreferredSize(new Dimension(jScrollPane2.getWidth(), 35));
        tableHeader.setFont(new Font("Time new roman", Font.BOLD, 12));
        tableHeader.setBackground(Color.red);
        
    }
    
    private void remarque_produitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remarque_produitFocusGained
        remarque_produit.setText("");
    }//GEN-LAST:event_remarque_produitFocusGained

    private void ImageProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseClicked

        UIManager.put("FileChooser.cancelButtonText","الغاء");
        JFileChooser chooserfile = new JFileChooser();
        chooserfile.setApproveButtonText("حفظ");
        int valShoice=chooserfile.showDialog(this,"اختر صورة المنتج");
        //int valShoice=chooserfile.showOpenDialog(this);

        if (valShoice==JFileChooser.APPROVE_OPTION) {
            //ProduitImageDesc=
            ProduitPicture=chooserfile.getSelectedFile();  // select
            ImageProduit.setText("");

            ImageIcon imageIcon = new ImageIcon(new ImageIcon(ProduitPicture.getAbsolutePath()).getImage().getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_DEFAULT));
            ImageProduit.setIcon(imageIcon);
            //ImageProduit.setIcon( new ImageIcon(ProduitImageDesc.getAbsolutePath()).getImage().getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_DEFAULT));  // set Icon to produit label
        }else{

            ImageIcon imageIcon = new ImageIcon(getClass().getResource("/imgs/addimgPrd2.png"));

            ImageProduit.setIcon(imageIcon);
            ImageProduit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            ImageProduit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            ImageProduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }//GEN-LAST:event_ImageProduitMouseClicked

    private void ImageProduitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseEntered
   //     jLabel2.setVisible(true);
    }//GEN-LAST:event_ImageProduitMouseEntered

    private void ImageProduitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseExited
      //  jLabel2.setVisible(false);
    }//GEN-LAST:event_ImageProduitMouseExited

    private void jMenu3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu3StateChanged

    }//GEN-LAST:event_jMenu3StateChanged

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        //JOptionPane.showMessageDialog(null, "Test MenuItem");
     //   jPanel8.setVisible(true);
       // jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
//        this.setLocationRelativeTo(this);
    }//GEN-LAST:event_formWindowStateChanged

    private void ProductsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsTableMouseClicked
    
        int SelRow=ProductsTable.getSelectedRow();
//        if (SelRow==-1) {
//            JOptionPane.showMessageDialog(null, "Test Selected Rows");
//        }
        
        int ID_Produit=(int) ProductsTable.getValueAt(SelRow, 7);
        
        
        
        try {
            produitstockGetDat.RetreiveProduct(ID_Produit);
            
            Ref_produit.setText(produitstockGetDat.getReference_Pro());
            Desg_produit.setText(produitstockGetDat.getDesignation());
            //Catg_produit.select(categorieGetData.GetNameCategorieById(produitstockGetDat.getID_Categorie()));
            Catg_produit_cmb.setSelectedItem(categorieGetData.GetNameCategorieById(produitstockGetDat.getID_Categorie()));
            DateDormatField.setText(new SimpleDateFormat("dd/MM/yyyy").format(produitstockGetDat.getDate_Expiration()));
            Prix_Achat_prd.setText(String.valueOf( produitstockGetDat.getPrix_Achat()) );
            prixVente_produit.setText(String.valueOf(produitstockGetDat.getPrix_Vente()));
            LocalStock.setSelectedItem(stockGetData.GetLocalStockById(produitstockGetDat.getId_Stocke()));   //GetLocalStockById
            QuantityStok_produit.setText(String.valueOf(produitstockGetDat.getQty_En_Stock()));
            NbrPcsInQty_produit.setText("20");
            Postion_produit.setText(produitstockGetDat.getPosition_Produit());
            MinStok_produit.setText(String.valueOf(produitstockGetDat.getMin_Stock()));
            ShowScreen_produit.setSelected(produitstockGetDat.isCheck_Produit());
            remarque_produit.setText(produitstockGetDat.getRemarque_Produit());
            InputStream StreamImg=produitstockGetDat.getProductPict();
            int SizeOfByte=StreamImg.available();
            byte [] arrayImgByte=new byte[SizeOfByte];
            StreamImg.read(arrayImgByte);
            ImageProduit.setText("");
            ImageProduit.setIcon(new ImageIcon(new ImageIcon(arrayImgByte).getImage().
                    getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_SMOOTH) ));
        } catch (IOException ex) {
            Logger.getLogger(FormAddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_ProductsTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Test SetMnomnic a");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnNewPrductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewPrductActionPerformed
            
            add_prduct.FillDataCategorie();
            add_prduct.FillDataStockLocal();
            add_prduct.FillDataUnits();
            add_prduct.setLocationRelativeTo(null);
            add_prduct.setVisible(true);
    }//GEN-LAST:event_BtnNewPrductActionPerformed

    private void check_update_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_update_addActionPerformed
        
        //(check_update_add.isSelected())?BtnInerSavUpd.setEnabled(true):BtnInerSavUpd.setEnabled(false);
        if (check_update_add.isSelected()) 
            BtnInerSavUpd.setEnabled(true);
        else BtnInerSavUpd.setEnabled(false);
        
    }//GEN-LAST:event_check_update_addActionPerformed
    public void FillDataStockLocal(){
        LocalStock.removeAllItems();
        Iterator<Stocke> itr=stockGetData.GetlistDataLocaleStock().iterator();
        Stocke next;
        while (itr.hasNext()) {
            next = itr.next();
            LocalStock.addItem(next.getLocale_Stocke());
        }
        itr=null;
        next=null;
    }
    /*************************************/
       public void FillDataUnits(){
        UnitForQuantity_produit.removeAllItems();
        
        Iterator<Unit> itr=unit_GetData.GetlistDataUnits().iterator();
        Unit next;
        while (itr.hasNext()) {
            next = itr.next();
            UnitForQuantity_produit.addItem(next.getUnit_Name());
        }
        itr=null;
        next=null;
    }
    /***************************************/
    public void FillDataCategorie(){
    //Catg_produit.removeAll();
    Catg_produit_cmb.removeAllItems();
    categorieGetData.GetListOfCategories(); // fill arrayList for Categories
    Iterator<Categorie> itr=categorieGetData.getListCategorie().iterator(); // get ArrayList.To Iterator()
    Categorie next;
    
    while (itr.hasNext()) {
            next = itr.next();
           // Catg_produit.addItem(next.getName_Ctg());
            Catg_produit_cmb.addItem(next.getName_Ctg());
        }
    }
    /***************Fill Data Table******************/
    public void FillTableOfProductList(){
        DefaultTableModel df;
        df = (DefaultTableModel) ProductsTable.getModel();
        df.setRowCount(0);
        produitstockGetDat.FillArrayOfProdutStock();
        Iterator<produit_stock> itr=produitstockGetDat.getListProduitStock().iterator(); // get ArrayList.To Iterator()
        produit_stock next;
        Object [] arg;
        arg = new Object[8];
        
    while (itr.hasNext()) {
            next = itr.next();
            arg[0]=next.getQty_En_Stock();
            arg[1]=next.getPrix_Vente();
            arg[2]=next.getPrix_Achat();
            arg[3]= unit_GetData.GetUnitName(next.getId_Unit()); 
            arg[4]=categorieGetData.GetNameCategorieById(next.getID_Categorie());
            arg[5]=next.getDesignation();
            arg[6]=next.getReference_Pro();
            arg[7]=next.getID_Prod();
            df.addRow(arg);
        }
    }
    
    // to optimise the work we need to create field of arrays of object geted not called the methods of arrays
    
    
    /************************************************/
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private matjarokom.ui.view.ButtonView BtnInerSavUpd;
    private matjarokom.ui.view.ButtonView BtnNewPrduct;
    private javax.swing.JComboBox<String> Catg_produit_cmb;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JCheckBox CheckDateExp_produit;
    private javax.swing.JCheckBox CheckDateExp_produit1;
    private javax.swing.JFormattedTextField DateDormatField;
    private javax.swing.JTextField Desg_produit;
    private javax.swing.JTextField Forns_produit;
    private javax.swing.JLabel Frn_ID10;
    private javax.swing.JLabel Frn_ID11;
    private javax.swing.JLabel Frn_ID15;
    private javax.swing.JLabel Frn_ID19;
    private javax.swing.JLabel Frn_ID21;
    private javax.swing.JLabel Frn_ID22;
    private javax.swing.JLabel Frn_ID23;
    private javax.swing.JLabel Frn_ID24;
    private javax.swing.JLabel Frn_ID28;
    private javax.swing.JLabel Frn_ID29;
    private javax.swing.JLabel Frn_ID5;
    private javax.swing.JLabel Frn_ID6;
    private javax.swing.JLabel Frn_ID9;
    private javax.swing.JLabel ImageProduit;
    private javax.swing.JComboBox<String> LocalStock;
    private javax.swing.JTextField MinStok_produit;
    private javax.swing.JTextField NbrPcsInQty_produit;
    private javax.swing.JLabel Nbr_Pcs_label1;
    private javax.swing.JTextField Postion_produit;
    private javax.swing.JTextField Prix_Achat_prd;
    private javax.swing.JTable ProductsTable;
    private javax.swing.JTextField QuantityStok_produit;
    private javax.swing.JTextField Ref_produit;
    private javax.swing.JCheckBox ShowScreen_produit;
    private javax.swing.JCheckBox ShowScreen_produit1;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JTextField Stock_produit;
    private javax.swing.JTextField TxtPrdPrix9;
    private javax.swing.JComboBox<String> UnitForQuantity_produit;
    private javax.swing.JComboBox<String> Unit_produit;
    private matjarokom.ui.view.ButtonView buttonView1;
    private matjarokom.ui.view.ButtonView buttonView3;
    private matjarokom.ui.view.ButtonView buttonView4;
    private javax.swing.JCheckBox check_update_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField prixVente_produit;
    private javax.swing.JTextArea remarque_produit;
    // End of variables declaration//GEN-END:variables
}
