/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 /*
As the name depicts, view represents the visualization of data received from the model.
The view layer consists of output of application or user interface. 
It sends the requested data to the client, that is fetched from model layer by controller.
 */
package matjarokom.ui.view;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import matjarokom.Control.com.RoundedLineBorder;
import matjarokom.Model.com.Fournisseur;

/**
 *
 * @author farid
 */
public class FournissourView extends javax.swing.JDialog {

    private Fournisseur fournissour;
    RoundedLineBorder roundedLineBorder =new RoundedLineBorder(Color.BLACK, 1, 10, true);
    JTextField tabTxtView[];
    String FacebookTxt, YoutubeTxt;
    char Op_Add_Updt='A'; // use chaoice to add Supplier Or Update
    char fb_yb = 'f';// this char to choice Fb or youtube to save init f
    dialgMsgUnits UnitCnfMsg;

    /**
     * Creates new form SupplierView
     * @param parent
     * @param modal
     */
    public FournissourView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        UnitCnfMsg = new dialgMsgUnits(this, modal);
        initComponents();
        this.tabTxtView = new JTextField[]{Nom_fr, Prenm_fr, Adress_Fr, Tel_Email_fr, Entreprise_fr, N_Registre, N_compte, NIF_fr, Credit_fr, Debit_fr, WebSite_fr,URL_SocialMedia_fb1,URL_SocialMedia_yb};
        fournissour = new Fournisseur();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Entreprise_fr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NIF_fr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        N_compte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        N_Registre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Credit_fr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Debit_fr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Remarque_fr = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nom_fr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Prenm_fr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Adress_Fr = new javax.swing.JTextField();
        labChechInput = new javax.swing.JLabel();
        PicFornView = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        N_Order_Frn = new javax.swing.JLabel();
        buttonView4 = new matjarokom.ui.view.ButtonView();
        UpdateFrnButton = new matjarokom.ui.view.ButtonView();
        buttonView3 = new matjarokom.ui.view.ButtonView();
        buttonView1 = new matjarokom.ui.view.ButtonView();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Tel_Email_fr = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        WebSite_fr = new javax.swing.JTextField();
        URL_SocialMedia_fb1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        URL_SocialMedia_yb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("شاشة الموردين");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "اسم الشركة", "اللقب", "الاسم", "الرقم"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Entreprise_fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Entreprise_fr.setForeground(new java.awt.Color(153, 153, 153));
        Entreprise_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entreprise_fr.setText("اسم الشركة");
        Entreprise_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Entreprise_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Entreprise_frKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("اسم الشركة:");

        NIF_fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NIF_fr.setForeground(new java.awt.Color(153, 153, 153));
        NIF_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NIF_fr.setText("NIF");
        NIF_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NIF_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NIF_frKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("رقم الحساب :");

        N_compte.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        N_compte.setForeground(new java.awt.Color(153, 153, 153));
        N_compte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        N_compte.setText("رقم الحساب");
        N_compte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        N_compte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                N_compteKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(": NIF");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("رقم السجل:");

        N_Registre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        N_Registre.setForeground(new java.awt.Color(153, 153, 153));
        N_Registre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        N_Registre.setText("رقم السجل");
        N_Registre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        N_Registre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                N_RegistreKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("دائن:");

        Credit_fr.setForeground(new java.awt.Color(153, 153, 153));
        Credit_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Credit_fr.setText("00.00");
        Credit_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Credit_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Credit_frKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("مدين:");

        Debit_fr.setForeground(new java.awt.Color(153, 153, 153));
        Debit_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Debit_fr.setText("00.00");
        Debit_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Debit_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Debit_frKeyPressed(evt);
            }
        });

        Remarque_fr.setColumns(20);
        Remarque_fr.setForeground(new java.awt.Color(153, 153, 153));
        Remarque_fr.setRows(5);
        Remarque_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Remarque_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Remarque_frKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Remarque_fr);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("ملاحظات:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(N_Registre, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(NIF_fr)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Debit_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Credit_fr)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(N_compte, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(Entreprise_fr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entreprise_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_Registre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIF_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Credit_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Debit_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("اسم المورد:");

        Nom_fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Nom_fr.setForeground(new java.awt.Color(153, 153, 153));
        Nom_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nom_fr.setText("الاسم");
        Nom_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Nom_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nom_frKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("لقب المورد:");

        Prenm_fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Prenm_fr.setForeground(new java.awt.Color(153, 153, 153));
        Prenm_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Prenm_fr.setText("اللقب");
        Prenm_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Prenm_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Prenm_frKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("عنوان المورد:");

        Adress_Fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Adress_Fr.setForeground(new java.awt.Color(153, 153, 153));
        Adress_Fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Adress_Fr.setText("عنوان المورد");
        Adress_Fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Adress_Fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Adress_FrKeyPressed(evt);
            }
        });

        labChechInput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Prenm_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nom_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labChechInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Adress_Fr, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nom_fr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addComponent(Prenm_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labChechInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adress_Fr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PicFornView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PicFornView.setText("الصورة");
        PicFornView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("تحميل");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });

        N_Order_Frn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        N_Order_Frn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N_Order_Frn.setText("01");

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("اضاقة");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        buttonView4.setRounded(true);
        buttonView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView4ActionPerformed(evt);
            }
        });

        UpdateFrnButton.setBackground(new java.awt.Color(0, 102, 102));
        UpdateFrnButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateFrnButton.setText("تعديل");
        UpdateFrnButton.setBackgroundPainted(true);
        UpdateFrnButton.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        UpdateFrnButton.setRounded(true);
        UpdateFrnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateFrnButtonActionPerformed(evt);
            }
        });

        buttonView3.setBackground(new java.awt.Color(0, 102, 102));
        buttonView3.setForeground(new java.awt.Color(255, 255, 255));
        buttonView3.setText("مسح");
        buttonView3.setBackgroundPainted(true);
        buttonView3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        buttonView3.setRounded(true);
        buttonView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView3ActionPerformed(evt);
            }
        });

        buttonView1.setBackground(new java.awt.Color(0, 102, 102));
        buttonView1.setForeground(new java.awt.Color(255, 255, 255));
        buttonView1.setText("رجوع");
        buttonView1.setBackgroundPainted(true);
        buttonView1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        buttonView1.setRounded(true);
        buttonView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/facebook-icon.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/youtube-icon.jpg"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("البريد الالكتروني\nرقم الهاتف:");

        Tel_Email_fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tel_Email_fr.setForeground(new java.awt.Color(153, 153, 153));
        Tel_Email_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tel_Email_fr.setText("البريد الالكتروني او رقم الهاتف");
        Tel_Email_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tel_Email_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tel_Email_frKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("الموقع الالكتروني:");

        WebSite_fr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        WebSite_fr.setForeground(new java.awt.Color(153, 153, 153));
        WebSite_fr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WebSite_fr.setText("www.MyWebSite.com");
        WebSite_fr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WebSite_fr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WebSite_frKeyPressed(evt);
            }
        });

        URL_SocialMedia_fb1.setForeground(new java.awt.Color(153, 153, 153));
        URL_SocialMedia_fb1.setText("https://www.facebook.com/username");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("صفحة الفيسبوك:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("قناة اليوتيب:");

        URL_SocialMedia_yb.setForeground(new java.awt.Color(153, 153, 153));
        URL_SocialMedia_yb.setText("https://www.youtube.com/c/youtubeChannel");
        URL_SocialMedia_yb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        URL_SocialMedia_yb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                URL_SocialMedia_ybFocusGained(evt);
            }
        });
        URL_SocialMedia_yb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URL_SocialMedia_ybActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/paste.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/paste.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WebSite_fr, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tel_Email_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(URL_SocialMedia_fb1)
                            .addComponent(URL_SocialMedia_yb, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tel_Email_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebSite_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(URL_SocialMedia_fb1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(URL_SocialMedia_yb))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(N_Order_Frn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel9))
                                    .addComponent(PicFornView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(UpdateFrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(N_Order_Frn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PicFornView, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateFrnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView4ActionPerformed

        //UnitCnfMsg.SetMsgTextShow("هل تريد تأكيد العملية");
        if (!isChecked()) {
            labChechInput.setText("تأكد من تعبئة الحقول الاساسية");
            labChechInput.setForeground(Color.red);
            
            return;
        }
        // stop when Empty all fields after save object (last task)

        String Nom_Fournisseur = Nom_fr.getText();
        String PrenFrn = Prenm_fr.getText();

        String Adrs_Fr = (Adress_Fr.getText().equals("عنوان المورد")) ? "" : Adress_Fr.getText();
        String Tel_Email = (Tel_Email_fr.getText().equals("البريد الالكتروني او رقم الهاتف")) ? "" : Tel_Email_fr.getText();
        //String NumAssur=N_Assurance.getText();
        String Nif_frn = (NIF_fr.getText().equals("NIF")) ? "" : NIF_fr.getText();

        float debit = Float.valueOf(Debit_fr.getText());
        float credit = Float.valueOf(Credit_fr.getText());

        String N_entreprise = (Entreprise_fr.getText().equals("اسم الشركة")) ? "" : Entreprise_fr.getText();
        //String N_entreprise=Entreprise_fr.getText();

        String N_registre = (N_Registre.getText().equals("رقم السجل")) ? "" : N_Registre.getText();

        String nCompte = (N_compte.getText().equals("رقم الحساب")) ? "" : N_compte.getText();

        String WebSite = (WebSite_fr.getText().equals("www.MyWebSite.com")) ? "" : WebSite_fr.getText();
        FacebookTxt=URL_SocialMedia_fb1.getText();
        YoutubeTxt=URL_SocialMedia_yb.getText();
        
        String remarque = Remarque_fr.getText();

        //String N_registre=N_Registre.getText();
        //String nCompte=N_compte.getText();
        this.fournissour = new Fournisseur(0, Nom_Fournisseur, PrenFrn, Adrs_Fr, Tel_Email, Nif_frn, debit,
                credit, N_entreprise, nCompte, N_registre, WebSite, remarque,FacebookTxt,YoutubeTxt);
        this.fournissour.Add_Fournissour();

        DefaultTableModel df = (DefaultTableModel) this.jTable1.getModel();
        df.addRow(fournissour.GetArrayDataFournissourToView()); // add New Row without call method to view Data In table
        //HintText();
        //FillDataTableFournissour(this.fournissour.GetListFournisseur()); // filling after add 
        
    }//GEN-LAST:event_buttonView4ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        JFileChooser chooserWind = new JFileChooser();
        int choice = chooserWind.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION) {
            java.io.File ImageF;
            ImageF = chooserWind.getSelectedFile();

            javax.swing.ImageIcon imgIcon = new ImageIcon(new ImageIcon(ImageF.getAbsolutePath()).getImage().getScaledInstance(PicFornView.getWidth(), PicFornView.getHeight(), Image.SCALE_DEFAULT));
            PicFornView.setIcon(imgIcon);

        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setBackground(Color.gray);
        jLabel9.setOpaque(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void UpdateFrnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateFrnButtonActionPerformed

        UnitCnfMsg.SetMsgTextShow("تأكيد عملية التعديل");
        dialgMsgUnits.ShowmessgConf();
        byte conf = dialgMsgUnits.getYes_No();
        if (conf == 1) {

            int N_Ordre = Integer.parseInt(N_Order_Frn.getText());
            String Nom_Fournisseur = Nom_fr.getText();
            String PrenFrn = Prenm_fr.getText();
            String Adrs_Fr = Adress_Fr.getText();
            String Tel_Email = Tel_Email_fr.getText();
            String Nif_frn = NIF_fr.getText();
            //String NumAssur=N_Assurance.getText();
            float debit = Float.valueOf(Debit_fr.getText());
            float credit = Float.valueOf(Credit_fr.getText());
            String N_entreprise = Entreprise_fr.getText();
            String N_registre = N_Registre.getText();
            String nCompte = N_compte.getText();
            String WebSite = WebSite_fr.getText();
            FacebookTxt=URL_SocialMedia_fb1.getText();
            YoutubeTxt=URL_SocialMedia_yb.getText();
            String Remarque = Remarque_fr.getText();
            
            this.fournissour = new Fournisseur(N_Ordre, Nom_Fournisseur, PrenFrn, Adrs_Fr, Tel_Email,
                    Nif_frn, debit, credit, N_entreprise, nCompte, N_registre, WebSite, Remarque,FacebookTxt,YoutubeTxt);
            this.fournissour.UpdateFournisseur(N_Ordre);// Function to Update Frn New Fournisseur fournissour.getID_Fournisseur()
            FillDataTableFournissour(fournissour.GetListFournisseur());
        }


    }//GEN-LAST:event_UpdateFrnButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DisplayChoiceRowDataInGUI();// display data of fournisseur object when select fornisseur from jtable
        changeText_ViewsColor();

    }//GEN-LAST:event_jTable1MouseClicked

    private void Nom_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nom_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Prenm_fr.requestFocus();
        }
    }//GEN-LAST:event_Nom_frKeyPressed

    private void Prenm_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Prenm_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Adress_Fr.requestFocus();
        }
    }//GEN-LAST:event_Prenm_frKeyPressed

    private void Adress_FrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Adress_FrKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adress_FrKeyPressed

    private void Entreprise_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Entreprise_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            N_Registre.requestFocus();

        }
    }//GEN-LAST:event_Entreprise_frKeyPressed

    private void N_RegistreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_N_RegistreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            N_compte.requestFocus();
        }
    }//GEN-LAST:event_N_RegistreKeyPressed

    private void N_compteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_N_compteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            NIF_fr.requestFocus();
        }
    }//GEN-LAST:event_N_compteKeyPressed

    private void NIF_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIF_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Credit_fr.requestFocus();
        }
    }//GEN-LAST:event_NIF_frKeyPressed

    private void Credit_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Credit_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Debit_fr.requestFocus();
        }
    }//GEN-LAST:event_Credit_frKeyPressed

    private void Debit_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Debit_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Remarque_fr.requestFocus();
        }
    }//GEN-LAST:event_Debit_frKeyPressed

    private void Remarque_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Remarque_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonView4.requestFocus();
        }
    }//GEN-LAST:event_Remarque_frKeyPressed

    private void Tel_Email_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tel_Email_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            WebSite_fr.requestFocus();
        }
    }//GEN-LAST:event_Tel_Email_frKeyPressed

    private void WebSite_frKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WebSite_frKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Entreprise_fr.requestFocus();
        }
    }//GEN-LAST:event_WebSite_frKeyPressed

    private void buttonView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView3ActionPerformed
        ResetTextFields();
    }//GEN-LAST:event_buttonView3ActionPerformed

    private void buttonView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView1ActionPerformed

    }//GEN-LAST:event_buttonView1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Test si Visible but never showing in interactive Button
//        if (Op_Add_Updt=='A') {             //this is operation for Add New Fournsseur 
//        URL_SocialMedia_fb.setVisible(true);
//        BtnSaveSocialMd.setVisible(true);
//        URL_SocialMedia_fb.setText("https://www.facebook.com/Farid.Soft");
//        fb_yb = 'f';
//
//        }else {
        
            
     
     String url =URL_SocialMedia_fb1.getText();
     //url= "https://www.facebook.com/MustafaHosny";
     Desktop dt = Desktop.getDesktop();
     URI uri = null;
            try {
                uri = new URI(url);
                dt.browse(uri);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(FournissourView.class.getName()).log(Level.SEVERE, null, ex);
            }
     


        
            
        //}
        
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        URL_SocialMedia_fb.setVisible(true);
//        BtnSaveSocialMd.setVisible(true);
//        URL_SocialMedia_fb.setText("https://www.youtube.com/c/youtubeChannel");
//        fb_yb = 'y';
//       String url = "www.stackoverflow.com";
//Desktop desktop = java.awt.Desktop.getDesktop();
//desktop.browse(url);
     String url =URL_SocialMedia_fb1.getText();
     url= "https://www.youtube.com";
     Desktop dt = Desktop.getDesktop();
     URI uri = null;
            try {
                uri = new URI(url);
                dt.browse(uri);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(FournissourView.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void URL_SocialMedia_ybFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_URL_SocialMedia_ybFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_URL_SocialMedia_ybFocusGained

    private void URL_SocialMedia_ybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URL_SocialMedia_ybActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URL_SocialMedia_ybActionPerformed

    private void onPaste(){
    Clipboard c = Toolkit.getDefaultToolkit().getSystemClipboard();
    Transferable t = c.getContents(this);
    if (t == null)
        
        return;
    try {
        URL_SocialMedia_fb1.setText((String) t.getTransferData(DataFlavor.stringFlavor));
    } catch (UnsupportedFlavorException | IOException e){
        e.printStackTrace();
    }//try
}//onPaste
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.onPaste();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Stop here at 15:04 finish task keyPressed Enter to next compenent
    private boolean isChecked() {

        boolean x = (Nom_fr.getText().equals("") || Nom_fr.getText().equals("الاسم") || Prenm_fr.getText().equals("اللقب") || Prenm_fr.getText().equals("")); //(Nom= emmpt: Vr  )

        /**
         * Nom=vide :True prenom=vide : true ==> x =True NotChecked return False
         * Nom=vide :True prenom=Non vide : false ==> x =True NotChecked return
         * False Nom=Non vide :False prenom=vide : true ==> x =True NotChecked
         * return False Nom=Non vide :false prenom=Non vide : true ==> x =false
         * IsChecked return True 
        *
         */
        System.out.println(!x);
        return !x; // True for checked false for else
    }

    
    public void ResetTextFields() {
        N_Order_Frn.setText(fournissour.maxIdFournisseur() + 1 + "");
        
        Nom_fr.setText("الاسم");
        Nom_fr.setForeground(Color.gray);

        Prenm_fr.setText("اللقب");
        Prenm_fr.setForeground(Color.gray);

        Adress_Fr.setText("عنوان المورد");
        Adress_Fr.setForeground(Color.gray);

        Tel_Email_fr.setText("البريد الالكتروني او رقم الهاتف");
        Tel_Email_fr.setForeground(Color.gray);

        WebSite_fr.setText("www.MyWebSite.com");
        WebSite_fr.setForeground(Color.gray);

        Entreprise_fr.setText("اسم الشركة");
        Entreprise_fr.setForeground(Color.gray);

        N_compte.setText("رقم الحساب");
        N_compte.setForeground(Color.gray);

        N_Registre.setText("رقم السجل");
        N_Registre.setForeground(Color.gray);

        NIF_fr.setText("NIF");
        NIF_fr.setForeground(Color.gray);

        Credit_fr.setText("00.00");
        Credit_fr.setForeground(Color.gray);

        Debit_fr.setText("00.00");
        Debit_fr.setForeground(Color.gray);
        
        URL_SocialMedia_fb1.setText("https://www.facebook.com/username");
        URL_SocialMedia_fb1.setForeground(Color.gray);
        FacebookTxt="";
        URL_SocialMedia_yb.setText("https://www.youtube.com/c/youtubeChannel");
        URL_SocialMedia_yb.setForeground(Color.gray);
        YoutubeTxt="";
        
        Remarque_fr.setText("");

        //Remarque_fr
    }

    public void DisplayChoiceRowDataInGUI() {
        int RowSel = jTable1.getSelectedRow();
        int id_frn = (int) jTable1.getValueAt(RowSel, 3);

        fournissour.GetInformationFromDBByID(id_frn);// fill fileds of fournisseur with data Of dataBase
        N_Order_Frn.setText("" + fournissour.getID_Fournisseur());

        Nom_fr.setText(fournissour.getNom_Fournisseur());
        Prenm_fr.setText(fournissour.getPrenom_Fournisseur());
        Adress_Fr.setText(fournissour.getAdress());
        Tel_Email_fr.setText(fournissour.getTel_email());
        Entreprise_fr.setText(fournissour.getN_Enterprise());
        N_Registre.setText(fournissour.getN_Registre());
        N_compte.setText(fournissour.getN_Compte());
        NIF_fr.setText(fournissour.getNif());
        Credit_fr.setText(fournissour.getCredit() + "");
        Debit_fr.setText(fournissour.getDebit() + "");
        WebSite_fr.setText(fournissour.getWebSite());
        FacebookTxt=fournissour.getFacebook();
        YoutubeTxt=fournissour.getYoutube();
        System.out.println("FacebookTxt/"+FacebookTxt);
        System.out.println("YoutubeTXT:"+YoutubeTxt);    
        
        URL_SocialMedia_fb1.setText(FacebookTxt);
        URL_SocialMedia_yb.setText(YoutubeTxt);
        
        Remarque_fr.setText(fournissour.getRemarque());
        
    }

    /**
     * Change color of JtextField of Fournisseur Form Wwhen call function in
     * update data 
     *
     */
    private void changeText_ViewsColor() {
        N_Order_Frn.setText("" + fournissour.getID_Fournisseur());

        Nom_fr.setForeground(Color.black);
        Prenm_fr.setForeground(Color.black);
        Adress_Fr.setForeground(Color.black);
        Tel_Email_fr.setForeground(Color.black);
        Entreprise_fr.setForeground(Color.black);
        N_Registre.setForeground(Color.black);
        N_compte.setForeground(Color.black);
        NIF_fr.setForeground(Color.black);
        Credit_fr.setForeground(Color.black);
        Debit_fr.setForeground(Color.black);
        WebSite_fr.setForeground(Color.black);
        URL_SocialMedia_fb1.setForeground(Color.black);
        URL_SocialMedia_yb.setForeground(Color.black);
        Remarque_fr.setForeground(Color.black);

    }

    /**
     * This Function uses in some function to disable and enable input data in
     * form fornisseur or updata data only with permission
     *
     */
    private void Disable_EnableJtextFildsFormFournisseur(boolean En_or_Dis) {
        //N_Order_Frn.setText(""+fournissour.getID_Fournisseur());

        Nom_fr.setEnabled(En_or_Dis);
        Prenm_fr.setEnabled(En_or_Dis);
        Adress_Fr.setEnabled(En_or_Dis);
        Tel_Email_fr.setEnabled(En_or_Dis);
        Entreprise_fr.setEnabled(En_or_Dis);
        N_Registre.setEnabled(En_or_Dis);
        N_compte.setEnabled(En_or_Dis);
        NIF_fr.setEnabled(En_or_Dis);
        Credit_fr.setEnabled(En_or_Dis);
        Debit_fr.setEnabled(En_or_Dis);
        WebSite_fr.setEnabled(En_or_Dis);
        Remarque_fr.setEnabled(En_or_Dis);

    }
    
    public void SetBorderOfAllComponent(){
    
    for (JTextField textField : tabTxtView) {
    
    textField.setBorder(roundedLineBorder);
    }
    }

    public void HintText() {
            for (JTextField textField : tabTxtView) {
            textField.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent e) {
                    if (textField.getText().equals("الاسم")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                        if (!labChechInput.getText().equals("")) {// when user focused in Nom or labChechInputchange
                            labChechInput.setText("");
                        }

                    }
                    if (textField.getText().equals("اللقب")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                        if (!labChechInput.getText().equals("")) {// when user focused in Nom or labChechInputchange
                            labChechInput.setText("");
                        }
                    }
                    if (textField.getText().equals("عنوان المورد")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("البريد الالكتروني او رقم الهاتف")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }

                    if (textField.getText().equals("www.MyWebSite.com")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }

                    if (textField.getText().equals("اسم الشركة")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("رقم السجل")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("رقم الحساب")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("NIF")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("00.00")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("https://www.facebook.com/username")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    if (textField.getText().equals("https://www.youtube.com/c/youtubeChannel")) {
                        textField.setText("");
                        textField.setForeground(Color.black);
                    }
                    

                }

                @Override
                public void focusLost(FocusEvent e) {
                    if (textField.equals(Nom_fr) && textField.getText().equals("")) {
                        textField.setText("الاسم");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(Prenm_fr) && textField.getText().equals("")) {
                        textField.setText("اللقب");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(Adress_Fr) && textField.getText().equals("")) {
                        textField.setText("عنوان المورد");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(Tel_Email_fr) && textField.getText().equals("")) {
                        textField.setText("البريد الالكتروني او رقم الهاتف");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(WebSite_fr) && textField.getText().equals("")) {
                        textField.setText("www.MyWebSite.com");
                        textField.setForeground(Color.gray);
                    }

                    if (textField.equals(Entreprise_fr) && textField.getText().equals("")) {
                        textField.setText("اسم الشركة");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(N_Registre) && textField.getText().equals("")) {
                        textField.setText("رقم السجل");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(N_compte) && textField.getText().equals("")) {
                        textField.setText("رقم الحساب");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(NIF_fr) && textField.getText().equals("")) {
                        textField.setText("NIF");
                        textField.setForeground(Color.gray);
                    }
                    if ((textField.equals(Credit_fr) || textField.equals(Debit_fr)) && textField.getText().equals("")) {
                        textField.setText("00.00");
                        textField.setForeground(Color.gray);
                    }
                    
                    if (textField.equals(URL_SocialMedia_fb1) && textField.getText().equals("")) {
                        textField.setText("https://www.facebook.com/username");
                        textField.setForeground(Color.gray);
                    }
                    if (textField.equals(URL_SocialMedia_yb) && textField.getText().equals("")) {
                        textField.setText("https://www.youtube.com/c/youtubeChannel");
                        textField.setForeground(Color.gray);
                    }
                }
            });
        }

    }

    public void FillDataTableFournissour(ArrayList<Fournisseur> listFrn) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        for (Fournisseur next : listFrn) {
            Object[] args = {next.getN_Enterprise(), next.getPrenom_Fournisseur(), next.getNom_Fournisseur(), next.getID_Fournisseur()};
            tableModel.addRow(args);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FournissourView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FournissourView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FournissourView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FournissourView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FournissourView dialog = new FournissourView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                Fournisseur f = new Fournisseur();
                dialog.FillDataTableFournissour(f.GetListFournisseur());
                dialog.SetBorderOfAllComponent();
                dialog.HintText();
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adress_Fr;
    private javax.swing.JTextField Credit_fr;
    private javax.swing.JTextField Debit_fr;
    private javax.swing.JTextField Entreprise_fr;
    private javax.swing.JTextField NIF_fr;
    private javax.swing.JLabel N_Order_Frn;
    private javax.swing.JTextField N_Registre;
    private javax.swing.JTextField N_compte;
    private javax.swing.JTextField Nom_fr;
    private javax.swing.JLabel PicFornView;
    private javax.swing.JTextField Prenm_fr;
    private javax.swing.JTextArea Remarque_fr;
    private javax.swing.JTextField Tel_Email_fr;
    private javax.swing.JTextField URL_SocialMedia_fb1;
    private javax.swing.JTextField URL_SocialMedia_yb;
    private matjarokom.ui.view.ButtonView UpdateFrnButton;
    private javax.swing.JTextField WebSite_fr;
    private matjarokom.ui.view.ButtonView buttonView1;
    private matjarokom.ui.view.ButtonView buttonView3;
    private matjarokom.ui.view.ButtonView buttonView4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labChechInput;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fournissour
     */
    public Fournisseur getFournissour() {
        return fournissour;
    }
}
