/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matjarokom.ui.view;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author horizon
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame02
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Frn_ID48 = new javax.swing.JLabel();
        TxtPrdQty3 = new javax.swing.JTextField();
        TxtPrdPrix2 = new javax.swing.JTextField();
        Frn_ID14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Frn_ID25 = new javax.swing.JLabel();
        Frn_ID5 = new javax.swing.JLabel();
        Frn_ID7 = new javax.swing.JLabel();
        TxtPrdPrix = new javax.swing.JTextField();
        Frn_ID28 = new javax.swing.JLabel();
        TxtPrdPrix1 = new javax.swing.JTextField();
        TxtPrdQty1 = new javax.swing.JTextField();
        Frn_ID47 = new javax.swing.JLabel();
        TxtPrdDesg = new javax.swing.JTextField();
        Frn_ID3 = new javax.swing.JLabel();
        Frn_ID12 = new javax.swing.JLabel();
        TxtPrdDesg1 = new javax.swing.JTextField();
        Frn_ID26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        ListFournisseur = new javax.swing.JComboBox<>();
        ListCategorie = new javax.swing.JComboBox<>();
        Frn_ID8 = new javax.swing.JLabel();
        Frn_ID4 = new javax.swing.JLabel();
        txtDatArrivage = new javax.swing.JFormattedTextField();
        TxtPrdQty = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1183, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ادارة المنتجــات", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1087, 70));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 378));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(true);

        jLabel1.setText("jLabel1");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(536, 536, 536))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("jTextField1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("رقم الفاتورة:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("تاريخ الفاتورة:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("سعر الفاتورة:");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("اسم الشركة:");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("تفاصيل المنتجات:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("اسم المورد:");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("اسم الشركة:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "المخزن", "تعديل", "صورة", "ملاحظات", "حد الطلب", "الكمية", "سعر البيع", "سعر الشراء", "وحدة الشراء", "اسم الصنف", "المنتج", "الباركود", "اسم المنتج"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 0, 153));
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(51, 0, 51));
        JTableHeader header = jTable1.getTableHeader();
        header.setForeground(Color.BLACK);
        header.setBackground(Color.WHITE);
        header.setFont(new Font("Times New Roman", Font.BOLD, 16));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        Frn_ID48.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID48.setText("الحد الأدنى للمخزون:");

        TxtPrdQty3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdQty3.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdQty3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdQty3.setText("00");
        TxtPrdQty3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdQty3FocusGained(evt);
            }
        });
        TxtPrdQty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdQty3ActionPerformed(evt);
            }
        });
        TxtPrdQty3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdQty3KeyTyped(evt);
            }
        });

        TxtPrdPrix2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdPrix2.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix2.setText("00");
        TxtPrdPrix2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix2FocusLost(evt);
            }
        });
        TxtPrdPrix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix2ActionPerformed(evt);
            }
        });
        TxtPrdPrix2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix2KeyTyped(evt);
            }
        });

        Frn_ID14.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID14.setText("عدد القطـع:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));

        Frn_ID25.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID25.setText("الوحدة   :");

        Frn_ID5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID5.setText("الكميـــة:");

        Frn_ID7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID7.setText("سعر الشــراء :");

        TxtPrdPrix.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdPrix.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix.setText("00.00");
        TxtPrdPrix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrixFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrixFocusLost(evt);
            }
        });
        TxtPrdPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrixActionPerformed(evt);
            }
        });
        TxtPrdPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrixKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrixKeyTyped(evt);
            }
        });

        Frn_ID28.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID28.setText("سعر البيع :");

        TxtPrdPrix1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdPrix1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix1.setText("00.00");
        TxtPrdPrix1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix1FocusLost(evt);
            }
        });
        TxtPrdPrix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix1ActionPerformed(evt);
            }
        });
        TxtPrdPrix1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix1KeyTyped(evt);
            }
        });

        TxtPrdQty1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdQty1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdQty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdQty1.setText("00");
        TxtPrdQty1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdQty1FocusGained(evt);
            }
        });
        TxtPrdQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdQty1ActionPerformed(evt);
            }
        });
        TxtPrdQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdQty1KeyTyped(evt);
            }
        });

        Frn_ID47.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID47.setText("رصيد المخزون الافتتاحي:");

        TxtPrdDesg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdDesg.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdDesg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdDesg.setText("Designation de produit ");
        TxtPrdDesg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdDesgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdDesgFocusLost(evt);
            }
        });
        TxtPrdDesg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyTyped(evt);
            }
        });

        Frn_ID3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID3.setText(" المنتــوج :");

        Frn_ID12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID12.setText("الباركـود :");

        TxtPrdDesg1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdDesg1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdDesg1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdDesg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdDesg1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdDesg1FocusLost(evt);
            }
        });
        TxtPrdDesg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyTyped(evt);
            }
        });

        Frn_ID26.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID26.setText("الكمية المتوفرة:");

        ListFournisseur.setEditable(true);
        ListFournisseur.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ListFournisseur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر المورد..." }));
        ListFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListFournisseurActionPerformed(evt);
            }
        });

        ListCategorie.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ListCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner un categorie ..." }));
        ListCategorie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListCategorieFocusGained(evt);
            }
        });

        Frn_ID8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID8.setText(" المورد :");

        Frn_ID4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID4.setText("النـــوع :");

        try {
            txtDatArrivage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDatArrivage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDatArrivage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDatArrivageFocusLost(evt);
            }
        });

        TxtPrdQty.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtPrdQty.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdQty.setText("00");
        TxtPrdQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdQtyFocusGained(evt);
            }
        });
        TxtPrdQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdQtyActionPerformed(evt);
            }
        });
        TxtPrdQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdQtyKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jTextField5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 247, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatArrivage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(Frn_ID48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(ListFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Frn_ID8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Frn_ID26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Frn_ID47, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdPrix1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(Frn_ID28, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(ListCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Frn_ID4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdDesg1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Frn_ID12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdDesg, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(Frn_ID3))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Frn_ID7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPrdQty, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Frn_ID5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TxtPrdPrix2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Frn_ID14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Frn_ID25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatArrivage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Frn_ID26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(TxtPrdQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Frn_ID47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(TxtPrdPrix1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Frn_ID28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(TxtPrdQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Frn_ID48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Frn_ID4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPrdDesg1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPrdDesg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtPrdPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(TxtPrdPrix2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Frn_ID14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPrdQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Frn_ID25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 40));

        jMenu2.setBorder(null);
        jMenu2.setText("الشـــركة");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("العنوان");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setText("بيـــانات أســاسيـة");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu3StateChanged(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setBorder(null);
        jMenu1.setText("عمـلاء و مورديـن");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu1);

        jMenu4.setBorder(null);
        jMenu4.setText("المبيعـات");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(null);
        jMenu5.setText("المشتريــات");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(null);
        jMenu6.setText("القبــض و الصرف");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu6);

        jMenu7.setBorder(null);
        jMenu7.setText("الحســـابات");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu7);

        jMenu8.setBorder(null);
        jMenu8.setText("اعدادات");
        jMenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu8);

        jMenu9.setBorder(null);
        jMenu9.setText("البحـث");
        jMenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu9);

        jMenu10.setBorder(null);
        jMenu10.setText("الخدمات");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu10);

        jMenu11.setBorder(null);
        jMenu11.setText("مسـاعدة");
        jMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu11);

        jMenu12.setBorder(null);
        jMenu12.setText("خروج");
        jMenu12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu12);

        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        JOptionPane.showMessageDialog(null, "Test MenuItem");
        jPanel8.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu3StateChanged
          JOptionPane.showMessageDialog(null, "Test MenuItem");
        jPanel8.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenu3StateChanged

    private void TxtPrdQty3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdQty3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty3FocusGained

    private void TxtPrdQty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdQty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty3ActionPerformed

    private void TxtPrdQty3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdQty3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty3KeyTyped

    private void TxtPrdPrix2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix2FocusGained

    private void TxtPrdPrix2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix2FocusLost

    private void TxtPrdPrix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix2ActionPerformed

    private void TxtPrdPrix2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix2KeyPressed

    private void TxtPrdPrix2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix2KeyTyped

    private void TxtPrdPrixFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrixFocusGained
        // TODO add your handling code here:
        /*  if (TxtPrdPrix.getText().equals("Prix du produit")) {
            TxtPrdPrix.setText("");
        }
        TxtPrdPrix.setForeground(Color.black);*/
    }//GEN-LAST:event_TxtPrdPrixFocusGained

    private void TxtPrdPrixFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrixFocusLost
        // TODO add your handling code here:
        // CalculePrix();
        //JOptionPane.showMessageDialog(null, "The value is"+Integer.parseInt(TxtPrdPrix.getText()));
    }//GEN-LAST:event_TxtPrdPrixFocusLost

    private void TxtPrdPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrixActionPerformed

    private void TxtPrdPrixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrixKeyPressed
        // TODO add your handling code here:
        /*
        if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB) {
            CalculePrix(TxtPrdQty,TxtPrdPrix,ResPrdQtyAndPrix);
        }
        */
    }//GEN-LAST:event_TxtPrdPrixKeyPressed

    private void TxtPrdPrixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrixKeyTyped
        // TODO add your handling code here:
        /*    char c=evt.getKeyChar();

        if ( !(Character.isDigit(c)

            ||(c==KeyEvent.VK_DELETE)

            ||(c==KeyEvent.VK_BACK_SPACE)
            ||(c==KeyEvent.VK_PERIOD))
        )
        {

            //         JOptionPane.showMessageDialog(null, "I AMA kEY nOT nUMERIC");
            getToolkit().beep();

            evt.consume();

        }*/
    }//GEN-LAST:event_TxtPrdPrixKeyTyped

    private void TxtPrdPrix1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1FocusGained

    private void TxtPrdPrix1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1FocusLost

    private void TxtPrdPrix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1ActionPerformed

    private void TxtPrdPrix1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1KeyPressed

    private void TxtPrdPrix1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1KeyTyped

    private void TxtPrdQty1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdQty1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty1FocusGained

    private void TxtPrdQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty1ActionPerformed

    private void TxtPrdQty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdQty1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty1KeyTyped

    private void TxtPrdDesgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesgFocusGained

        if (TxtPrdDesg.getText().equals("Designation de produit ")) {
            TxtPrdDesg.setText("");
            System.out.println("Homme.TxtPrdDesgFocusGained()" + "  The TestIs Designation de produit AND Color is Gray ");

        }
        System.out.println("  The TestIs Designation de produit AND Color is Black ");
    }//GEN-LAST:event_TxtPrdDesgFocusGained

    private void TxtPrdDesgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesgFocusLost
        // TODO add your handling code here:
        // enq=null;
        /*
        if(!(TxtPrdDesg.getText().equals("") ||TxtPrdDesg.getText().equals("Designation de produit ") ) ){
            JOptionPane.showMessageDialog(null, "Test Vide In event Loset ANd dESIGNATION PRODUIT ");

            Prd_Stck.GetID_Product(TxtPrdDesg.getText());
            TxtPrdID.setEnabled(false);
            TxtPrdID.setForeground(Color.black);

            int numPrd=Prd_Stck.getID_Prod() ;

            if (etat==1) {

                TxtPrdID.setText(numPrd+"");

                ListCategorie.setSelectedItem(Prd_Stck.GetCategorieProduct(numPrd));

                CheckNew.setText("Exist Deja");
                CheckNew.setForeground(Color.green);
                CheckNew.setSelected(false);

            }else
            {

                int last=Prd_Stck.GetLastProduct();    //return last number of product
                TxtPrdID.setText((last+1)+"");  //textfield de prd==last +1 because is it new
                CheckNew.setSelected(true);
                CheckNew.setForeground(Color.red);

            }
        }else{

            JOptionPane.showMessageDialog(null, "Fill the Text Of designation");
            //TxtPrdDesg.requestFocus();
            //ListCategorie.requestFocus();
        }*/
    }//GEN-LAST:event_TxtPrdDesgFocusLost

    private void TxtPrdDesgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyPressed
        /*    System.out.println("I ma in Pressed ..........Key ");
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_BACK_SPACE:
            break;

            case KeyEvent.VK_ENTER:

            TxtPrdDesg.setText(TxtPrdDesg.getText());
            break;
            default :

            // EventQueue.invokeLater(new Runnable() {
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {

                        System.out.println("W ere Are called The autocomplete");

                        String txt = TxtPrdDesg.getText();

                        etat=autocompleteDesprd(txt,TxtPrdDesg,Name);    //this by object produit stock

                        System.out.println("W ere Are EXECUTE The autocomplete");
                        // etat=new produit_stock().autocomplete(TxtPrdDesg, txt);
                    }
                });
                break;
            }
            */
    }//GEN-LAST:event_TxtPrdDesgKeyPressed

    private void TxtPrdDesgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesgKeyReleased

    private void TxtPrdDesgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyTyped
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null  ,"the code typed "+ evt.getKeyCode()+" "+evt.getKeyChar());
    }//GEN-LAST:event_TxtPrdDesgKeyTyped

    private void TxtPrdDesg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesg1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1FocusGained

    private void TxtPrdDesg1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesg1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1FocusLost

    private void TxtPrdDesg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyPressed

    private void TxtPrdDesg1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyReleased

    private void TxtPrdDesg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyTyped

    private void ListFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListFournisseurActionPerformed
        // TODO add your handling code here://                                              //dernier point stoped
        /*
        FournisserRemplissage.GetNumFournisseur((String) ListFournisseur.getSelectedItem());

        Frn_ID_Num.setText(""+FournisserRemplissage.getID_Fournisseur());*/
    }//GEN-LAST:event_ListFournisseurActionPerformed

    private void ListCategorieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListCategorieFocusGained
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, "Tessssssssssssssssssssst");
    }//GEN-LAST:event_ListCategorieFocusGained

    private void txtDatArrivageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatArrivageFocusLost
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, "the text is "+txtDatArrivage.getText());
        /*
        String DateArrivageIni="  /  /    ";

        SimpleDateFormat format=new SimpleDateFormat("dd/MM/YYYY");
        Date date = null;
        try {
            date=format.parse(txtDatArrivage.getText());
            //date instanceof Date;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "ERROR IN PARSE Date String "+ex.getMessage());
            txtDatArrivage.requestFocus();
        }
        if (! (date instanceof Date) ) {

            JOptionPane.showMessageDialog(null, "ERROR IN  text is "+txtDatArrivage.getText());
        }
        */
    }//GEN-LAST:event_txtDatArrivageFocusLost

    private void TxtPrdQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdQtyFocusGained
        // TODO add your handling code here:
        /*     if (TxtPrdQty.getText().equals("Quantité")) {
            TxtPrdQty.setText("");
        }
        TxtPrdQty.setForeground(Color.black);*/
    }//GEN-LAST:event_TxtPrdQtyFocusGained

    private void TxtPrdQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQtyActionPerformed

    private void TxtPrdQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdQtyKeyTyped
        // TODO add your handling code here:
        /*    char c=evt.getKeyChar();  if ( !(Character.isDigit(c) ||(c==KeyEvent.VK_DELETE) ||(c==KeyEvent.VK_BACK_SPACE)))
        {
            getToolkit().beep();
            evt.consume();}*/
    }//GEN-LAST:event_TxtPrdQtyKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frn_ID12;
    private javax.swing.JLabel Frn_ID14;
    private javax.swing.JLabel Frn_ID25;
    private javax.swing.JLabel Frn_ID26;
    private javax.swing.JLabel Frn_ID28;
    private javax.swing.JLabel Frn_ID3;
    private javax.swing.JLabel Frn_ID4;
    private javax.swing.JLabel Frn_ID47;
    private javax.swing.JLabel Frn_ID48;
    private javax.swing.JLabel Frn_ID5;
    private javax.swing.JLabel Frn_ID7;
    private javax.swing.JLabel Frn_ID8;
    private javax.swing.JComboBox<String> ListCategorie;
    private javax.swing.JComboBox<String> ListFournisseur;
    private javax.swing.JTextField TxtPrdDesg;
    private javax.swing.JTextField TxtPrdDesg1;
    private javax.swing.JTextField TxtPrdPrix;
    private javax.swing.JTextField TxtPrdPrix1;
    private javax.swing.JTextField TxtPrdPrix2;
    private javax.swing.JTextField TxtPrdQty;
    private javax.swing.JTextField TxtPrdQty1;
    private javax.swing.JTextField TxtPrdQty3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JFormattedTextField txtDatArrivage;
    // End of variables declaration//GEN-END:variables
}
