/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matjarokom.ui.view;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author horizon
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame02
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Frn_ID48 = new javax.swing.JLabel();
        TxtPrdQty3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        Frn_ID25 = new javax.swing.JLabel();
        Frn_ID5 = new javax.swing.JLabel();
        Frn_ID7 = new javax.swing.JLabel();
        TxtPrdPrix = new javax.swing.JTextField();
        Frn_ID28 = new javax.swing.JLabel();
        TxtPrdPrix1 = new javax.swing.JTextField();
        TxtPrdQty1 = new javax.swing.JTextField();
        Frn_ID47 = new javax.swing.JLabel();
        TxtPrdDesg = new javax.swing.JTextField();
        Frn_ID3 = new javax.swing.JLabel();
        Frn_ID12 = new javax.swing.JLabel();
        TxtPrdDesg1 = new javax.swing.JTextField();
        Frn_ID26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        ListFournisseur = new javax.swing.JComboBox<>();
        ListCategorie = new javax.swing.JComboBox<>();
        Frn_ID8 = new javax.swing.JLabel();
        Frn_ID4 = new javax.swing.JLabel();
        txtDatArrivage = new javax.swing.JFormattedTextField();
        TxtPrdQty = new javax.swing.JTextField();
        TxtPrdPrix3 = new javax.swing.JTextField();
        Frn_ID15 = new javax.swing.JLabel();
        Frn_ID9 = new javax.swing.JLabel();
        Frn_ID16 = new javax.swing.JLabel();
        TxtPrdPrix4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDatArrivage1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1183, 600));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ادارة المنتجــات", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1087, 70));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 378));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(true);

        jLabel1.setText("jLabel1");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(536, 536, 536))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(1063, 600));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 120, 25));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(" رقــم الفاتورة :");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("تاريخ الفاتورة :");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 45, 62, 22));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("سعر الفاتورة:");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 70, 30));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 102, 32));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("اسم الشركة:");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 70, 30));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 102, 32));

        jLabel8.setText("تفاصيل المنتجات:");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 24));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("اسم المورد:");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 70, 30));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 90, 32));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 90, 32));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("اسم الشركة:");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "المخزن", "تعديل", "صورة", "ملاحظات", "حد الطلب", "الكمية", "سعر البيع", "سعر الشراء", "وحدة الشراء", "اسم الصنف", "المنتج", "الباركود", "اسم المنتج"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 0, 153));
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(51, 0, 51));
        JTableHeader header = jTable1.getTableHeader();
        header.setForeground(Color.BLACK);
        header.setBackground(Color.WHITE);
        header.setFont(new Font("Times New Roman", Font.BOLD, 16));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 451, 940, 190));

        Frn_ID48.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID48.setText("الحد الأدنى للمخزون :");
        jPanel8.add(Frn_ID48, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 122, 30));

        TxtPrdQty3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdQty3.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdQty3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdQty3.setText("00");
        TxtPrdQty3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdQty3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdQty3FocusGained(evt);
            }
        });
        TxtPrdQty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdQty3ActionPerformed(evt);
            }
        });
        TxtPrdQty3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdQty3KeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 171, 32));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 190, 32));

        Frn_ID25.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID25.setText("الوحدة :");
        jPanel8.add(Frn_ID25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 59, 30));

        Frn_ID5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID5.setText("الكميـــة :");
        jPanel8.add(Frn_ID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 59, 30));

        Frn_ID7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID7.setText("سعر الشــراء :");
        jPanel8.add(Frn_ID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, 30));

        TxtPrdPrix.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix.setText("00.00");
        TxtPrdPrix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrixFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrixFocusLost(evt);
            }
        });
        TxtPrdPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrixActionPerformed(evt);
            }
        });
        TxtPrdPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrixKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrixKeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 380, 240, 32));

        Frn_ID28.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID28.setText("سعر البيع :");
        jPanel8.add(Frn_ID28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 122, 30));

        TxtPrdPrix1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix1.setText("00.00");
        TxtPrdPrix1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix1FocusLost(evt);
            }
        });
        TxtPrdPrix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix1ActionPerformed(evt);
            }
        });
        TxtPrdPrix1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix1KeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdPrix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 171, 32));

        TxtPrdQty1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdQty1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdQty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdQty1.setText("00");
        TxtPrdQty1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdQty1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdQty1FocusGained(evt);
            }
        });
        TxtPrdQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdQty1ActionPerformed(evt);
            }
        });
        TxtPrdQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdQty1KeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 171, 32));

        Frn_ID47.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID47.setText("رصيد المخزون الافتتاحي :");
        jPanel8.add(Frn_ID47, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 120, 30));

        TxtPrdDesg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdDesg.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdDesg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdDesg.setText("Designation de produit ");
        TxtPrdDesg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdDesg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdDesgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdDesgFocusLost(evt);
            }
        });
        TxtPrdDesg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdDesg, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 210, 190, 32));

        Frn_ID3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID3.setText(" المنتـج :");
        jPanel8.add(Frn_ID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 210, 50, 30));

        Frn_ID12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID12.setText("الباركـود :");
        jPanel8.add(Frn_ID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 170, 50, 30));

        TxtPrdDesg1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdDesg1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdDesg1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdDesg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdDesg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdDesg1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdDesg1FocusLost(evt);
            }
        });
        TxtPrdDesg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdDesg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 170, 190, 32));

        Frn_ID26.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID26.setText("الكمية المتوفرة :");
        jPanel8.add(Frn_ID26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 171, 32));

        ListFournisseur.setEditable(true);
        ListFournisseur.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ListFournisseur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختر المورد..." }));
        ListFournisseur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListFournisseurActionPerformed(evt);
            }
        });
        jPanel8.add(ListFournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 171, 32));

        ListCategorie.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        ListCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner un categorie ..." }));
        ListCategorie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListCategorie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListCategorieFocusGained(evt);
            }
        });
        jPanel8.add(ListCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 170, 32));

        Frn_ID8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID8.setText(" المورد :");
        jPanel8.add(Frn_ID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 50, 30));

        Frn_ID4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID4.setText("النـــوع :");
        jPanel8.add(Frn_ID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 52, 31));

        txtDatArrivage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtDatArrivage.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDatArrivage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDatArrivage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDatArrivageFocusLost(evt);
            }
        });
        jPanel8.add(txtDatArrivage, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 45, 120, 22));

        TxtPrdQty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdQty.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdQty.setText("00");
        TxtPrdQty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdQtyFocusGained(evt);
            }
        });
        TxtPrdQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdQtyActionPerformed(evt);
            }
        });
        TxtPrdQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdQtyKeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 250, 190, 32));

        TxtPrdPrix3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix3.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix3.setText("00");
        TxtPrdPrix3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix3FocusLost(evt);
            }
        });
        TxtPrdPrix3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix3ActionPerformed(evt);
            }
        });
        TxtPrdPrix3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix3KeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdPrix3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 70, 32));

        Frn_ID15.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID15.setText("سعر القطعة :");
        jPanel8.add(Frn_ID15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 65, 30));

        Frn_ID9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID9.setText("سعر الشــراء :");
        jPanel8.add(Frn_ID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, -1, 30));

        Frn_ID16.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID16.setText("عدد القطـع :");
        jPanel8.add(Frn_ID16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 65, 30));

        TxtPrdPrix4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix4.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix4.setText("00");
        TxtPrdPrix4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix4FocusLost(evt);
            }
        });
        TxtPrdPrix4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix4ActionPerformed(evt);
            }
        });
        TxtPrdPrix4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix4KeyTyped(evt);
            }
        });
        jPanel8.add(TxtPrdPrix4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 90, 32));

        jLabel4.setText("jLabel4");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 210, 40, 30));

        jLabel5.setText("jLabel4");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 40, 30));

        jLabel11.setText("jLabel4");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 170, 40, 30));

        jLabel12.setText("jLabel4");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 250, 40, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("تاريخ الفاتورة :");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 62, 25));

        txtDatArrivage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            txtDatArrivage1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDatArrivage1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDatArrivage1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDatArrivage1FocusLost(evt);
            }
        });
        jPanel8.add(txtDatArrivage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 120, 25));

        jLabel14.setBackground(new java.awt.Color(0, 102, 102));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("الفاتورة");
        //
        jLabel14.setToolTipText("");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 60, 40));

        jLabel15.setBackground(new java.awt.Color(0, 102, 102));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("بيانات");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setOpaque(true);
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 60, 40));

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 40));

        jMenu2.setBorder(null);
        jMenu2.setText("الشـــركة");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("العنوان");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setText("بيـــانات أســاسيـة");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu3StateChanged(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setBorder(null);
        jMenu1.setText("عمـلاء و مورديـن");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu1);

        jMenu4.setBorder(null);
        jMenu4.setText("المبيعـات");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(null);
        jMenu5.setText("المشتريــات");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(null);
        jMenu6.setText("القبــض و الصرف");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu6);

        jMenu7.setBorder(null);
        jMenu7.setText("الحســـابات");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu7);

        jMenu8.setBorder(null);
        jMenu8.setText("اعدادات");
        jMenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu8);

        jMenu9.setBorder(null);
        jMenu9.setText("البحـث");
        jMenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu9);

        jMenu10.setBorder(null);
        jMenu10.setText("الخدمات");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu10);

        jMenu11.setBorder(null);
        jMenu11.setText("مسـاعدة");
        jMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu11);

        jMenu12.setBorder(null);
        jMenu12.setText("خروج");
        jMenu12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu12);

        jMenuBar1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        JOptionPane.showMessageDialog(null, "Test MenuItem");
        jPanel8.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu3StateChanged
          JOptionPane.showMessageDialog(null, "Test MenuItem");
        jPanel8.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jMenu3StateChanged

    private void TxtPrdQty3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdQty3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty3FocusGained

    private void TxtPrdQty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdQty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty3ActionPerformed

    private void TxtPrdQty3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdQty3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty3KeyTyped

    private void TxtPrdPrixFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrixFocusGained
        // TODO add your handling code here:
        /*  if (TxtPrdPrix.getText().equals("Prix du produit")) {
            TxtPrdPrix.setText("");
        }
        TxtPrdPrix.setForeground(Color.black);*/
    }//GEN-LAST:event_TxtPrdPrixFocusGained

    private void TxtPrdPrixFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrixFocusLost
        // TODO add your handling code here:
        // CalculePrix();
        //JOptionPane.showMessageDialog(null, "The value is"+Integer.parseInt(TxtPrdPrix.getText()));
    }//GEN-LAST:event_TxtPrdPrixFocusLost

    private void TxtPrdPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrixActionPerformed

    private void TxtPrdPrixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrixKeyPressed
        // TODO add your handling code here:
        /*
        if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB) {
            CalculePrix(TxtPrdQty,TxtPrdPrix,ResPrdQtyAndPrix);
        }
        */
    }//GEN-LAST:event_TxtPrdPrixKeyPressed

    private void TxtPrdPrixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrixKeyTyped
        // TODO add your handling code here:
        /*    char c=evt.getKeyChar();

        if ( !(Character.isDigit(c)

            ||(c==KeyEvent.VK_DELETE)

            ||(c==KeyEvent.VK_BACK_SPACE)
            ||(c==KeyEvent.VK_PERIOD))
        )
        {

            //         JOptionPane.showMessageDialog(null, "I AMA kEY nOT nUMERIC");
            getToolkit().beep();

            evt.consume();

        }*/
    }//GEN-LAST:event_TxtPrdPrixKeyTyped

    private void TxtPrdPrix1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1FocusGained

    private void TxtPrdPrix1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1FocusLost

    private void TxtPrdPrix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1ActionPerformed

    private void TxtPrdPrix1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1KeyPressed

    private void TxtPrdPrix1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix1KeyTyped

    private void TxtPrdQty1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdQty1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty1FocusGained

    private void TxtPrdQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty1ActionPerformed

    private void TxtPrdQty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdQty1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQty1KeyTyped

    private void TxtPrdDesgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesgFocusGained

        if (TxtPrdDesg.getText().equals("Designation de produit ")) {
            TxtPrdDesg.setText("");
            System.out.println("Homme.TxtPrdDesgFocusGained()" + "  The TestIs Designation de produit AND Color is Gray ");

        }
        System.out.println("  The TestIs Designation de produit AND Color is Black ");
    }//GEN-LAST:event_TxtPrdDesgFocusGained

    private void TxtPrdDesgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesgFocusLost
        // TODO add your handling code here:
        // enq=null;
        /*
        if(!(TxtPrdDesg.getText().equals("") ||TxtPrdDesg.getText().equals("Designation de produit ") ) ){
            JOptionPane.showMessageDialog(null, "Test Vide In event Loset ANd dESIGNATION PRODUIT ");

            Prd_Stck.GetID_Product(TxtPrdDesg.getText());
            TxtPrdID.setEnabled(false);
            TxtPrdID.setForeground(Color.black);

            int numPrd=Prd_Stck.getID_Prod() ;

            if (etat==1) {

                TxtPrdID.setText(numPrd+"");

                ListCategorie.setSelectedItem(Prd_Stck.GetCategorieProduct(numPrd));

                CheckNew.setText("Exist Deja");
                CheckNew.setForeground(Color.green);
                CheckNew.setSelected(false);

            }else
            {

                int last=Prd_Stck.GetLastProduct();    //return last number of product
                TxtPrdID.setText((last+1)+"");  //textfield de prd==last +1 because is it new
                CheckNew.setSelected(true);
                CheckNew.setForeground(Color.red);

            }
        }else{

            JOptionPane.showMessageDialog(null, "Fill the Text Of designation");
            //TxtPrdDesg.requestFocus();
            //ListCategorie.requestFocus();
        }*/
    }//GEN-LAST:event_TxtPrdDesgFocusLost

    private void TxtPrdDesgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyPressed
        /*    System.out.println("I ma in Pressed ..........Key ");
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_BACK_SPACE:
            break;

            case KeyEvent.VK_ENTER:

            TxtPrdDesg.setText(TxtPrdDesg.getText());
            break;
            default :

            // EventQueue.invokeLater(new Runnable() {
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {

                        System.out.println("W ere Are called The autocomplete");

                        String txt = TxtPrdDesg.getText();

                        etat=autocompleteDesprd(txt,TxtPrdDesg,Name);    //this by object produit stock

                        System.out.println("W ere Are EXECUTE The autocomplete");
                        // etat=new produit_stock().autocomplete(TxtPrdDesg, txt);
                    }
                });
                break;
            }
            */
    }//GEN-LAST:event_TxtPrdDesgKeyPressed

    private void TxtPrdDesgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesgKeyReleased

    private void TxtPrdDesgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyTyped
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null  ,"the code typed "+ evt.getKeyCode()+" "+evt.getKeyChar());
    }//GEN-LAST:event_TxtPrdDesgKeyTyped

    private void TxtPrdDesg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesg1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1FocusGained

    private void TxtPrdDesg1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesg1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1FocusLost

    private void TxtPrdDesg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyPressed

    private void TxtPrdDesg1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyReleased

    private void TxtPrdDesg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyTyped

    private void ListFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListFournisseurActionPerformed
        // TODO add your handling code here://                                              //dernier point stoped
        /*
        FournisserRemplissage.GetNumFournisseur((String) ListFournisseur.getSelectedItem());

        Frn_ID_Num.setText(""+FournisserRemplissage.getID_Fournisseur());*/
    }//GEN-LAST:event_ListFournisseurActionPerformed

    private void ListCategorieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListCategorieFocusGained
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, "Tessssssssssssssssssssst");
    }//GEN-LAST:event_ListCategorieFocusGained

    private void txtDatArrivageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatArrivageFocusLost
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, "the text is "+txtDatArrivage.getText());
        /*
        String DateArrivageIni="  /  /    ";

        SimpleDateFormat format=new SimpleDateFormat("dd/MM/YYYY");
        Date date = null;
        try {
            date=format.parse(txtDatArrivage.getText());
            //date instanceof Date;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "ERROR IN PARSE Date String "+ex.getMessage());
            txtDatArrivage.requestFocus();
        }
        if (! (date instanceof Date) ) {

            JOptionPane.showMessageDialog(null, "ERROR IN  text is "+txtDatArrivage.getText());
        }
        */
    }//GEN-LAST:event_txtDatArrivageFocusLost

    private void TxtPrdQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdQtyFocusGained
        // TODO add your handling code here:
        /*     if (TxtPrdQty.getText().equals("Quantité")) {
            TxtPrdQty.setText("");
        }
        TxtPrdQty.setForeground(Color.black);*/
    }//GEN-LAST:event_TxtPrdQtyFocusGained

    private void TxtPrdQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdQtyActionPerformed

    private void TxtPrdQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdQtyKeyTyped
        // TODO add your handling code here:
        /*    char c=evt.getKeyChar();  if ( !(Character.isDigit(c) ||(c==KeyEvent.VK_DELETE) ||(c==KeyEvent.VK_BACK_SPACE)))
        {
            getToolkit().beep();
            evt.consume();}*/
    }//GEN-LAST:event_TxtPrdQtyKeyTyped

    private void TxtPrdPrix3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix3FocusGained

    private void TxtPrdPrix3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix3FocusLost

    private void TxtPrdPrix3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix3ActionPerformed

    private void TxtPrdPrix3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix3KeyPressed

    private void TxtPrdPrix3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix3KeyTyped

    private void TxtPrdPrix4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix4FocusGained

    private void TxtPrdPrix4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix4FocusLost

    private void TxtPrdPrix4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix4ActionPerformed

    private void TxtPrdPrix4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix4KeyPressed

    private void TxtPrdPrix4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix4KeyTyped

    private void txtDatArrivage1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatArrivage1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatArrivage1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frn_ID12;
    private javax.swing.JLabel Frn_ID15;
    private javax.swing.JLabel Frn_ID16;
    private javax.swing.JLabel Frn_ID25;
    private javax.swing.JLabel Frn_ID26;
    private javax.swing.JLabel Frn_ID28;
    private javax.swing.JLabel Frn_ID3;
    private javax.swing.JLabel Frn_ID4;
    private javax.swing.JLabel Frn_ID47;
    private javax.swing.JLabel Frn_ID48;
    private javax.swing.JLabel Frn_ID5;
    private javax.swing.JLabel Frn_ID7;
    private javax.swing.JLabel Frn_ID8;
    private javax.swing.JLabel Frn_ID9;
    private javax.swing.JComboBox<String> ListCategorie;
    private javax.swing.JComboBox<String> ListFournisseur;
    private javax.swing.JTextField TxtPrdDesg;
    private javax.swing.JTextField TxtPrdDesg1;
    private javax.swing.JTextField TxtPrdPrix;
    private javax.swing.JTextField TxtPrdPrix1;
    private javax.swing.JTextField TxtPrdPrix3;
    private javax.swing.JTextField TxtPrdPrix4;
    private javax.swing.JTextField TxtPrdQty;
    private javax.swing.JTextField TxtPrdQty1;
    private javax.swing.JTextField TxtPrdQty3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JFormattedTextField txtDatArrivage;
    private javax.swing.JFormattedTextField txtDatArrivage1;
    // End of variables declaration//GEN-END:variables
}
