/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matjarokom.ui.view;

import javax.swing.JOptionPane;

/**
 *
 * @author horizon
 */
public class produitView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public produitView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtPrdDesg1 = new javax.swing.JTextField();
        Frn_ID12 = new javax.swing.JLabel();
        Frn_ID3 = new javax.swing.JLabel();
        TxtPrdDesg = new javax.swing.JTextField();
        TxtPrdPrix = new javax.swing.JTextField();
        Nbr_Pcs_label = new javax.swing.JLabel();
        TxtPrdPrix5 = new javax.swing.JTextField();
        Frn_ID10 = new javax.swing.JLabel();
        Frn_ID9 = new javax.swing.JLabel();
        Frn_ID4 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jTextField6 = new javax.swing.JTextField();
        Frn_ID26 = new javax.swing.JLabel();
        Frn_ID27 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        Frn_ID16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Frn_ID18 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        TxtPrdPrix6 = new javax.swing.JTextField();
        Frn_ID13 = new javax.swing.JLabel();
        Frn_ID14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtPrdDesg1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdDesg1.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdDesg1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdDesg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdDesg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdDesg1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdDesg1FocusLost(evt);
            }
        });
        TxtPrdDesg1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdDesg1KeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrdDesg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 218, 40));

        Frn_ID12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID12.setText("الباركـود :");
        jPanel1.add(Frn_ID12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 60, 40));

        Frn_ID3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID3.setText(" المنتـج :");
        jPanel1.add(Frn_ID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 60, 40));

        TxtPrdDesg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdDesg.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdDesg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdDesg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdDesg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdDesgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdDesgFocusLost(evt);
            }
        });
        TxtPrdDesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdDesgActionPerformed(evt);
            }
        });
        TxtPrdDesg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdDesgKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrdDesg, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 218, 40));

        TxtPrdPrix.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix.setText("00.00");
        TxtPrdPrix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrixFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrixFocusLost(evt);
            }
        });
        TxtPrdPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrixActionPerformed(evt);
            }
        });
        TxtPrdPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrixKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrixKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrdPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, 32));

        Nbr_Pcs_label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nbr_Pcs_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nbr_Pcs_label.setText("القطع داخل الوحدة :");
        jPanel1.add(Nbr_Pcs_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 97, 30));

        TxtPrdPrix5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix5.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix5.setText("00");
        TxtPrdPrix5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix5FocusLost(evt);
            }
        });
        TxtPrdPrix5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix5ActionPerformed(evt);
            }
        });
        TxtPrdPrix5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix5KeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrdPrix5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 230, 40));

        Frn_ID10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID10.setText("سعر البيع :");
        jPanel1.add(Frn_ID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 97, 40));

        Frn_ID9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID9.setText("سعر الشــراء :");
        jPanel1.add(Frn_ID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 97, 40));

        Frn_ID4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID4.setText("النـــوع :");
        jPanel1.add(Frn_ID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, -1, 40));
        jPanel1.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 219, 40));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 85, 32));

        Frn_ID26.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID26.setText("الكمية المتاحة :");
        jPanel1.add(Frn_ID26, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 32));

        Frn_ID27.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID27.setText("الوحدة :");
        jPanel1.add(Frn_ID27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 46, 32));

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));
        jComboBox2.setBorder(null);
        jComboBox2.setOpaque(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 160, 30));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 230, 30));

        Frn_ID16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID16.setText("مكان المنتج :");
        jPanel1.add(Frn_ID16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 90, 30));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "المخزن", "تعديل", "صورة", "ملاحظات", "حد الطلب", "الكمية", "سعر البيع", "سعر الشراء", "وحدة الشراء", "اسم الصنف", "المنتج", "الباركود", "اسم المنتج"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(51, 0, 153));
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(51, 0, 51));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 422, 1140, 230));

        jLabel1.setText("الاسعار القديمة");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 80, 30));

        Frn_ID18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID18.setText("ملاحظات :");
        jPanel1.add(Frn_ID18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 50, 30));

        jCheckBox2.setText("تاريخ الصلاحية :");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));
        jComboBox3.setBorder(null);
        jComboBox3.setOpaque(false);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 32));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 250));

        TxtPrdPrix6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix6.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix6.setText("00");
        TxtPrdPrix6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtPrdPrix6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrdPrix6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtPrdPrix6FocusLost(evt);
            }
        });
        TxtPrdPrix6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrdPrix6ActionPerformed(evt);
            }
        });
        TxtPrdPrix6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrdPrix6KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrdPrix6KeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrdPrix6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 230, 40));

        Frn_ID13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID13.setText("آخر تاريخ للشراء :");
        jPanel1.add(Frn_ID13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 97, 40));

        Frn_ID14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID14.setText("كمية اعادة الطلب :");
        jPanel1.add(Frn_ID14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 97, 40));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPrdDesg1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesg1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1FocusGained

    private void TxtPrdDesg1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesg1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1FocusLost

    private void TxtPrdDesg1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyPressed

    private void TxtPrdDesg1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyReleased

    private void TxtPrdDesg1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesg1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesg1KeyTyped

    private void TxtPrdDesgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesgFocusGained

        if (TxtPrdDesg.getText().equals("Designation de produit ")) {
            TxtPrdDesg.setText("");
            System.out.println("Homme.TxtPrdDesgFocusGained()" + "  The TestIs Designation de produit AND Color is Gray ");

        }
        System.out.println("  The TestIs Designation de produit AND Color is Black ");
    }//GEN-LAST:event_TxtPrdDesgFocusGained

    private void TxtPrdDesgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdDesgFocusLost
        // TODO add your handling code here:
        // enq=null;
        /*
        if(!(TxtPrdDesg.getText().equals("") ||TxtPrdDesg.getText().equals("Designation de produit ") ) ){
            JOptionPane.showMessageDialog(null, "Test Vide In event Loset ANd dESIGNATION PRODUIT ");

            Prd_Stck.GetID_Product(TxtPrdDesg.getText());
            TxtPrdID.setEnabled(false);
            TxtPrdID.setForeground(Color.black);

            int numPrd=Prd_Stck.getID_Prod() ;

            if (etat==1) {

                TxtPrdID.setText(numPrd+"");

                ListCategorie.setSelectedItem(Prd_Stck.GetCategorieProduct(numPrd));

                CheckNew.setText("Exist Deja");
                CheckNew.setForeground(Color.green);
                CheckNew.setSelected(false);

            }else
            {

                int last=Prd_Stck.GetLastProduct();    //return last number of product
                TxtPrdID.setText((last+1)+"");  //textfield de prd==last +1 because is it new
                CheckNew.setSelected(true);
                CheckNew.setForeground(Color.red);

            }
        }else{

            JOptionPane.showMessageDialog(null, "Fill the Text Of designation");
            //TxtPrdDesg.requestFocus();
            //ListCategorie.requestFocus();
        }*/
    }//GEN-LAST:event_TxtPrdDesgFocusLost

    private void TxtPrdDesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdDesgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesgActionPerformed

    private void TxtPrdDesgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyPressed
        /*    System.out.println("I ma in Pressed ..........Key ");
        switch (evt.getKeyCode()) {

            case KeyEvent.VK_BACK_SPACE:
            break;

            case KeyEvent.VK_ENTER:

            TxtPrdDesg.setText(TxtPrdDesg.getText());
            break;
            default :

            // EventQueue.invokeLater(new Runnable() {
                EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {

                        System.out.println("W ere Are called The autocomplete");

                        String txt = TxtPrdDesg.getText();

                        etat=autocompleteDesprd(txt,TxtPrdDesg,Name);    //this by object produit stock

                        System.out.println("W ere Are EXECUTE The autocomplete");
                        // etat=new produit_stock().autocomplete(TxtPrdDesg, txt);
                    }
                });
                break;
            }
            */
    }//GEN-LAST:event_TxtPrdDesgKeyPressed

    private void TxtPrdDesgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdDesgKeyReleased

    private void TxtPrdDesgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdDesgKeyTyped
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null  ,"the code typed "+ evt.getKeyCode()+" "+evt.getKeyChar());
    }//GEN-LAST:event_TxtPrdDesgKeyTyped

    private void TxtPrdPrixFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrixFocusGained
        // TODO add your handling code here:
        /*  if (TxtPrdPrix.getText().equals("Prix du produit")) {
            TxtPrdPrix.setText("");
        }
        TxtPrdPrix.setForeground(Color.black);*/
    }//GEN-LAST:event_TxtPrdPrixFocusGained

    private void TxtPrdPrixFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrixFocusLost
        // TODO add your handling code here:
        // CalculePrix();
        //JOptionPane.showMessageDialog(null, "The value is"+Integer.parseInt(TxtPrdPrix.getText()));
    }//GEN-LAST:event_TxtPrdPrixFocusLost

    private void TxtPrdPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrixActionPerformed

    private void TxtPrdPrixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrixKeyPressed
        // TODO add your handling code here:
        /*
        if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_TAB) {
            CalculePrix(TxtPrdQty,TxtPrdPrix,ResPrdQtyAndPrix);
        }
        */
    }//GEN-LAST:event_TxtPrdPrixKeyPressed

    private void TxtPrdPrixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrixKeyTyped
        // TODO add your handling code here:
        /*    char c=evt.getKeyChar();

        if ( !(Character.isDigit(c)

            ||(c==KeyEvent.VK_DELETE)

            ||(c==KeyEvent.VK_BACK_SPACE)
            ||(c==KeyEvent.VK_PERIOD))
        )
        {

            //         JOptionPane.showMessageDialog(null, "I AMA kEY nOT nUMERIC");
            getToolkit().beep();

            evt.consume();

        }*/
    }//GEN-LAST:event_TxtPrdPrixKeyTyped

    private void TxtPrdPrix5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix5FocusGained

    private void TxtPrdPrix5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix5FocusLost

    private void TxtPrdPrix5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix5ActionPerformed

    private void TxtPrdPrix5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix5KeyPressed

    private void TxtPrdPrix5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix5KeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void TxtPrdPrix6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix6FocusGained

    private void TxtPrdPrix6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrdPrix6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix6FocusLost

    private void TxtPrdPrix6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrdPrix6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix6ActionPerformed

    private void TxtPrdPrix6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix6KeyPressed

    private void TxtPrdPrix6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrdPrix6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrdPrix6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produitView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frn_ID10;
    private javax.swing.JLabel Frn_ID12;
    private javax.swing.JLabel Frn_ID13;
    private javax.swing.JLabel Frn_ID14;
    private javax.swing.JLabel Frn_ID16;
    private javax.swing.JLabel Frn_ID18;
    private javax.swing.JLabel Frn_ID26;
    private javax.swing.JLabel Frn_ID27;
    private javax.swing.JLabel Frn_ID3;
    private javax.swing.JLabel Frn_ID4;
    private javax.swing.JLabel Frn_ID9;
    private javax.swing.JLabel Nbr_Pcs_label;
    private javax.swing.JTextField TxtPrdDesg;
    private javax.swing.JTextField TxtPrdDesg1;
    private javax.swing.JTextField TxtPrdPrix;
    private javax.swing.JTextField TxtPrdPrix5;
    private javax.swing.JTextField TxtPrdPrix6;
    private java.awt.Choice choice1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
