/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matjarokom.ui.view;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import matjarokom.Control.com.RoundedLineBorder;

/**
 *
 * @author farid
 */
public class ProductSpeedAdd extends javax.swing.JFrame {

    private File ProduitPicture;
    
    RoundedLineBorder roundedLineBorder =new RoundedLineBorder(Color.BLACK, 1, 10, true);
    public ProductSpeedAdd() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageProduit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Ref_produit = new javax.swing.JTextField();
        Frn_ID15 = new javax.swing.JLabel();
        Frn_ID5 = new javax.swing.JLabel();
        Desg_produit = new javax.swing.JTextField();
        QuantityStok_produit = new javax.swing.JTextField();
        Frn_ID29 = new javax.swing.JLabel();
        UnitForQuantity_produit = new javax.swing.JComboBox<>();
        Frn_ID28 = new javax.swing.JLabel();
        Nbr_Pcs_label1 = new javax.swing.JLabel();
        NbrPcsInQty_produit = new javax.swing.JTextField();
        Frn_ID6 = new javax.swing.JLabel();
        CheckDateExp_produit1 = new javax.swing.JCheckBox();
        Prix_Achat_prd = new javax.swing.JTextField();
        Frn_ID9 = new javax.swing.JLabel();
        Frn_ID11 = new javax.swing.JLabel();
        prixVente_produit = new javax.swing.JTextField();
        Catg_produit_cmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Frn_ID19 = new javax.swing.JLabel();
        Frn_ID24 = new javax.swing.JLabel();
        Forns_produit = new javax.swing.JTextField();
        TxtPrdPrix9 = new javax.swing.JTextField();
        Frn_ID23 = new javax.swing.JLabel();
        Frn_ID22 = new javax.swing.JLabel();
        MinStok_produit = new javax.swing.JTextField();
        Frn_ID21 = new javax.swing.JLabel();
        Postion_produit = new javax.swing.JTextField();
        Frn_ID10 = new javax.swing.JLabel();
        LocalStock = new javax.swing.JComboBox<>();
        Stock_produit = new javax.swing.JTextField();
        Unit_produit = new javax.swing.JComboBox<>();
        CheckDateExp_produit = new javax.swing.JCheckBox();
        DateDormatField = new javax.swing.JFormattedTextField();
        Nbr_Pcs_label2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarque_produit = new javax.swing.JTextArea();
        ShowScreen_produit = new javax.swing.JCheckBox();
        ShowScreen_produit1 = new javax.swing.JCheckBox();
        Frn_ID25 = new javax.swing.JLabel();
        buttonView4 = new matjarokom.ui.view.ButtonView();
        buttonView1 = new matjarokom.ui.view.ButtonView();
        buttonView2 = new matjarokom.ui.view.ButtonView();
        buttonView3 = new matjarokom.ui.view.ButtonView();
        buttonView6 = new matjarokom.ui.view.ButtonView();
        buttonView7 = new matjarokom.ui.view.ButtonView();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ImageProduit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ImageProduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/addimgPrd2.png"))); // NOI18N
        ImageProduit.setText("الصورة");
        ImageProduit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ImageProduit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImageProduit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageProduit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ImageProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImageProduitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImageProduitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImageProduitMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(roundedLineBorder);

        Ref_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ref_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Ref_produit.setBorder(roundedLineBorder);

        Frn_ID15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID15.setText("الباركـود        :");

        Frn_ID5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID5.setText(" اسم المنتج    :");

        Desg_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Desg_produit.setForeground(new java.awt.Color(204, 204, 204));
        Desg_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Desg_produit.setBorder(roundedLineBorder);

        QuantityStok_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        QuantityStok_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityStok_produit.setText("20");
        QuantityStok_produit.setBorder(roundedLineBorder);

        Frn_ID29.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID29.setText("الوحدة ");

        UnitForQuantity_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        UnitForQuantity_produit.setBorder(null);
        UnitForQuantity_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UnitForQuantity_produit.setOpaque(false);

        Frn_ID28.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Frn_ID28.setText("الكمية المتاحة");

        Nbr_Pcs_label1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nbr_Pcs_label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nbr_Pcs_label1.setText("القطع داخل الوحدة");

        NbrPcsInQty_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NbrPcsInQty_produit.setForeground(new java.awt.Color(204, 204, 204));
        NbrPcsInQty_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        NbrPcsInQty_produit.setBorder(roundedLineBorder);

        Frn_ID6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID6.setText("التصنيف");

        CheckDateExp_produit1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        CheckDateExp_produit1.setText("تحتوي علئ عدة قطع");
        CheckDateExp_produit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckDateExp_produit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Prix_Achat_prd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Prix_Achat_prd.setForeground(new java.awt.Color(204, 204, 204));
        Prix_Achat_prd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Prix_Achat_prd.setText("00");
        Prix_Achat_prd.setBorder(roundedLineBorder);

        Frn_ID9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID9.setText("سعر الشــراء");

        Frn_ID11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID11.setText("سعر البيع");

        prixVente_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prixVente_produit.setForeground(new java.awt.Color(204, 204, 204));
        prixVente_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        prixVente_produit.setText("00");
        prixVente_produit.setBorder(roundedLineBorder);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nbr_Pcs_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NbrPcsInQty_produit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantityStok_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Frn_ID28, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Frn_ID29)
                                    .addComponent(UnitForQuantity_produit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckDateExp_produit1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Frn_ID5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Frn_ID15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Frn_ID11)
                                            .addComponent(prixVente_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2))
                                    .addComponent(Desg_produit)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Frn_ID9)
                                                .addComponent(Frn_ID6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Prix_Achat_prd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(1, 1, 1))
                                        .addComponent(Ref_produit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Catg_produit_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Frn_ID15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ref_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desg_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Frn_ID6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Catg_produit_cmb))
                .addGap(7, 7, 7)
                .addComponent(Frn_ID9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prix_Achat_prd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prixVente_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Frn_ID29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckDateExp_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnitForQuantity_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nbr_Pcs_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Frn_ID28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NbrPcsInQty_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(roundedLineBorder);

        Frn_ID19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID19.setText("مكان المنتج :");

        Frn_ID24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID24.setText("الموردين :");

        Forns_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Forns_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Forns_produit.setBorder(roundedLineBorder);

        TxtPrdPrix9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtPrdPrix9.setForeground(new java.awt.Color(204, 204, 204));
        TxtPrdPrix9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPrdPrix9.setText("00");
        TxtPrdPrix9.setBorder(roundedLineBorder);

        Frn_ID23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID23.setText("فوتير الشراء :");

        Frn_ID22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID22.setText("كمية اعادة الطلب :");

        MinStok_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MinStok_produit.setForeground(new java.awt.Color(204, 204, 204));
        MinStok_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MinStok_produit.setText("00");
        MinStok_produit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Frn_ID21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID21.setText("الكمية المتاحة   :");

        Postion_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Postion_produit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Postion_produit.setBorder(roundedLineBorder);

        Frn_ID10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID10.setText("المخزن :");

        LocalStock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LocalStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Stock_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Stock_produit.setForeground(new java.awt.Color(204, 204, 204));
        Stock_produit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Stock_produit.setText("00");
        Stock_produit.setBorder(roundedLineBorder);

        Unit_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Unit_produit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قطعة", "كرتونة", "لتر", "كيلو" }));
        Unit_produit.setBorder(null);
        Unit_produit.setOpaque(false);

        CheckDateExp_produit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CheckDateExp_produit.setText("منتج له تاريخ الصلاحية ");
        CheckDateExp_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckDateExp_produit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            DateDormatField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DateDormatField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Nbr_Pcs_label2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nbr_Pcs_label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nbr_Pcs_label2.setText("القطع داخل الوحدة");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C_Add_Mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Frn_ID23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frn_ID22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frn_ID19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Frn_ID10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frn_ID21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frn_ID24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(DateDormatField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckDateExp_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Forns_produit)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Nbr_Pcs_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPrdPrix9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Postion_produit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MinStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Unit_produit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stock_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Frn_ID22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinStok_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LocalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Postion_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Frn_ID21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Unit_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPrdPrix9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Frn_ID24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Forns_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(Nbr_Pcs_label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateDormatField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckDateExp_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("اضافة منتج جديد :");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("خصائص متقدمة");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        remarque_produit.setColumns(20);
        remarque_produit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        remarque_produit.setRows(4);
        remarque_produit.setText("\n");
        remarque_produit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الوصف", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        remarque_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        remarque_produit.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        remarque_produit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remarque_produitFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(remarque_produit);

        ShowScreen_produit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowScreen_produit.setText("اظهار المنتج في شاشة المبيعات");
        ShowScreen_produit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowScreen_produit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ShowScreen_produit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ShowScreen_produit1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ShowScreen_produit1.setSelected(true);
        ShowScreen_produit1.setText("اظهار اشعارات تخص المنتج ");
        ShowScreen_produit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowScreen_produit1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ShowScreen_produit1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Frn_ID25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Frn_ID25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Frn_ID25.setText("اضف الملاحظــة   :");

        buttonView4.setBackground(new java.awt.Color(0, 102, 102));
        buttonView4.setForeground(new java.awt.Color(255, 255, 255));
        buttonView4.setText("تحميل الصورة");
        buttonView4.setBackgroundPainted(true);
        buttonView4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView4.setRounded(true);

        buttonView1.setBackground(new java.awt.Color(153, 0, 0));
        buttonView1.setForeground(new java.awt.Color(255, 255, 255));
        buttonView1.setText("حفظ");
        buttonView1.setBackgroundPainted(true);
        buttonView1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView1.setRounded(true);

        buttonView2.setBackground(new java.awt.Color(0, 102, 102));
        buttonView2.setForeground(new java.awt.Color(255, 255, 255));
        buttonView2.setText("الرئيســية");
        buttonView2.setBackgroundPainted(true);
        buttonView2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView2.setRounded(true);

        buttonView3.setBackground(new java.awt.Color(0, 102, 102));
        buttonView3.setForeground(new java.awt.Color(255, 255, 255));
        buttonView3.setText("مسح");
        buttonView3.setBackgroundPainted(true);
        buttonView3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView3.setRounded(true);
        buttonView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView3ActionPerformed(evt);
            }
        });

        buttonView6.setBackground(new java.awt.Color(0, 102, 102));
        buttonView6.setForeground(new java.awt.Color(255, 255, 255));
        buttonView6.setText("الغـاء");
        buttonView6.setBackgroundPainted(true);
        buttonView6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView6.setRounded(true);

        buttonView7.setBackground(new java.awt.Color(0, 102, 102));
        buttonView7.setForeground(new java.awt.Color(255, 255, 255));
        buttonView7.setText("خروج");
        buttonView7.setBackgroundPainted(true);
        buttonView7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonView7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonView7.setRounded(true);
        buttonView7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView7ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(467, Short.MAX_VALUE)
                                .addComponent(jCheckBox1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buttonView4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(ImageProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Frn_ID25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ShowScreen_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ShowScreen_produit)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonView2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonView3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonView6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonView7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ImageProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonView4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ShowScreen_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowScreen_produit1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Frn_ID25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(buttonView1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonView2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(buttonView3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonView6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonView7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImageProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseClicked

        UIManager.put("FileChooser.cancelButtonText","الغاء");
        JFileChooser chooserfile = new JFileChooser();
        chooserfile.setApproveButtonText("حفظ");
        int valShoice=chooserfile.showDialog(this,"اختر صورة المنتج");
        //int valShoice=chooserfile.showOpenDialog(this);

        if (valShoice==JFileChooser.APPROVE_OPTION) {
            //ProduitImageDesc=
            ProduitPicture=chooserfile.getSelectedFile();  // select
            ImageProduit.setText("");

            ImageIcon imageIcon = new ImageIcon(new ImageIcon(ProduitPicture.getAbsolutePath()).getImage().getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_DEFAULT));
            ImageProduit.setIcon(imageIcon);
            //ImageProduit.setIcon( new ImageIcon(ProduitImageDesc.getAbsolutePath()).getImage().getScaledInstance(ImageProduit.getWidth(), ImageProduit.getHeight(), Image.SCALE_DEFAULT));  // set Icon to produit label
        }else{

            ImageIcon imageIcon = new ImageIcon(getClass().getResource("/imgs/addimgPrd2.png"));

            ImageProduit.setIcon(imageIcon);
            ImageProduit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            ImageProduit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            ImageProduit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }//GEN-LAST:event_ImageProduitMouseClicked

    private void ImageProduitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseEntered
        //     jLabel2.setVisible(true);
    }//GEN-LAST:event_ImageProduitMouseEntered

    private void ImageProduitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageProduitMouseExited
        //  jLabel2.setVisible(false);
    }//GEN-LAST:event_ImageProduitMouseExited

    private void remarque_produitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remarque_produitFocusGained
        remarque_produit.setText("");
    }//GEN-LAST:event_remarque_produitFocusGained

    private void buttonView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonView3ActionPerformed

    private void buttonView7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonView7ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Captions_Close_Hot.png"))); // NOI18N
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Captions_Close.png")));
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
//        this.setState(ICONIFIED);
//        if (R.isVisible()) {
//            R.setState(ICONIFIED);
//        } else if (Gs.isVisible()) {
//            Gs.setState(ICONIFIED);
//        } else {
//            F.setState(ICONIFIED);
//        }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Captions_Min_Hot.png"))); // NOI18N
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residence/Image/Captions_Min.png")));
    }//GEN-LAST:event_jLabel32MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSpeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSpeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSpeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSpeedAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSpeedAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Catg_produit_cmb;
    private javax.swing.JCheckBox CheckDateExp_produit;
    private javax.swing.JCheckBox CheckDateExp_produit1;
    private javax.swing.JFormattedTextField DateDormatField;
    private javax.swing.JTextField Desg_produit;
    private javax.swing.JTextField Forns_produit;
    private javax.swing.JLabel Frn_ID10;
    private javax.swing.JLabel Frn_ID11;
    private javax.swing.JLabel Frn_ID15;
    private javax.swing.JLabel Frn_ID19;
    private javax.swing.JLabel Frn_ID21;
    private javax.swing.JLabel Frn_ID22;
    private javax.swing.JLabel Frn_ID23;
    private javax.swing.JLabel Frn_ID24;
    private javax.swing.JLabel Frn_ID25;
    private javax.swing.JLabel Frn_ID28;
    private javax.swing.JLabel Frn_ID29;
    private javax.swing.JLabel Frn_ID5;
    private javax.swing.JLabel Frn_ID6;
    private javax.swing.JLabel Frn_ID9;
    private javax.swing.JLabel ImageProduit;
    private javax.swing.JComboBox<String> LocalStock;
    private javax.swing.JTextField MinStok_produit;
    private javax.swing.JTextField NbrPcsInQty_produit;
    private javax.swing.JLabel Nbr_Pcs_label1;
    private javax.swing.JLabel Nbr_Pcs_label2;
    private javax.swing.JTextField Postion_produit;
    private javax.swing.JTextField Prix_Achat_prd;
    private javax.swing.JTextField QuantityStok_produit;
    private javax.swing.JTextField Ref_produit;
    private javax.swing.JCheckBox ShowScreen_produit;
    private javax.swing.JCheckBox ShowScreen_produit1;
    private javax.swing.JTextField Stock_produit;
    private javax.swing.JTextField TxtPrdPrix9;
    private javax.swing.JComboBox<String> UnitForQuantity_produit;
    private javax.swing.JComboBox<String> Unit_produit;
    private matjarokom.ui.view.ButtonView buttonView1;
    private matjarokom.ui.view.ButtonView buttonView2;
    private matjarokom.ui.view.ButtonView buttonView3;
    private matjarokom.ui.view.ButtonView buttonView4;
    private matjarokom.ui.view.ButtonView buttonView6;
    private matjarokom.ui.view.ButtonView buttonView7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prixVente_produit;
    private javax.swing.JTextArea remarque_produit;
    // End of variables declaration//GEN-END:variables
}
